(function(gate, undefined) {
    var cardsetCode = "BM/S15"; // <-- IMPORTANT
    if(gate.cardsets == null) gate.cardsets = [];
    if(gate.cardset == null) gate.cardset = {};
    if($.inArray(cardsetCode, gate.cardsets) == -1) {
        gate.cardsets.push(cardsetCode);
        // Cardset Properties
        gate.cardset[cardsetCode] = {};
        gate.cardset[cardsetCode].SetName = "Bakemonogatari";
        gate.cardset[cardsetCode].SetCode = "BM";
        gate.cardset[cardsetCode].SetSide = "S";
        gate.cardset[cardsetCode].SetNum = "15";
        gate.cardset[cardsetCode].Cards = [];
        // Cardset Cards
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku, Easily Embarassed",
            CardNameJp: "恥ずかしがり屋 千石撫子",
            CardNo: "BM/S15-001",
            Rarity: "RR",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "6500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "Soul",
            Flavor: "Shinobu?",
            Effect: "[A] When this attacks, if \"A Girl Cursed\" is in the Climax Zone, search your Library for up to 1 ::Strange:: Character, reveal it, and put it in your hand. Shuffle your Library. [A] EXPERIENCE [(1)] When this is placed from hand to the Stage, if the sum of Levels of cards in your Level Zone is 4 or higher, you may pay cost. If so, search your Library for up to 1 \"A Girl Cursed\", reveal it, and put it in your hand. Shuffle your Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku, Easily Embarassed",
            CardNameJp: "恥ずかしがり屋 千石撫子",
            CardNo: "BM/S15-001S",
            Rarity: "SR",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "6500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "Soul",
            Flavor: "Shinobu?",
            Effect: "[A] When this attacks, if \"A Girl Cursed\" is in the Climax Zone, search your Library for up to 1 ::Strange:: Character, reveal it, and put it in your hand. Shuffle your Library. [A] EXPERIENCE [(1)] When this is placed from hand to the Stage, if the sum of Levels of cards in your Level Zone is 4 or higher, you may pay cost. If so, search your Library for up to 1 \"A Girl Cursed\", reveal it, and put it in your hand. Shuffle your Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi Hachikuji",
            CardNameJp: "八九寺真宵",
            CardNo: "BM/S15-002",
            Rarity: "RR",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Strange", "Spirit"],
            Triggers: "Soul",
            Flavor: "If you found it, please tell me",
            Effect: "[A] When this is placed from hand to the Stage, choose up to 2 other of your Characters. Those Characters gain +1000 Power and +1 Soul for the turn. [A] EXPERIENCE When this attacks, if the sum of Levels of cards in your Level Zone is 4 or higher, choose 1 of your Characters. That Character gains +1 Soul for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Koyomi Araragi on Mother's Day",
            CardNameJp: "母の日の阿良々木暦",
            CardNo: "BM/S15-003",
            Rarity: "R",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "1000",
            Soul: "1",
            Traits: ["Strange", "Blood"],
            Triggers: "None",
            Flavor: "I'll follow you-- confused?",
            Effect: "[C] All your other Characters gain +500 Power during your turn. [A] When this or another ::Strange:: Character is placed from hand to the Stage, you may look at the top of your Library. (Put it back where it was)"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi Hachikuji, Girl Who Keeps Wandering",
            CardNameJp: "さまよい続ける少女 八九寺真宵",
            CardNo: "BM/S15-004",
            Rarity: "R",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "1000",
            Soul: "1",
            Traits: ["Strange", "Spirit"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] If you have another ::Blood:: Character, this gains +2000 Power. [S] BRAINSTORM [(1) Rest 2 of your Characters] Reveal the top 4 cards of your Library and put them in the Waiting Room. For each Climax card revealed this way, search your Library for up to 1 ::Strange:: Character, reveal it, and put it in your hand. Shuffle your Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi Hachikuji, Girl Who Keeps Wandering",
            CardNameJp: "さまよい続ける少女 八九寺真宵",
            CardNo: "BM/S15-004S",
            Rarity: "SR",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "1000",
            Soul: "1",
            Traits: ["Strange", "Spirit"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] If you have another ::Blood:: Character, this gains +2000 Power. [S] BRAINSTORM [(1) Rest 2 of your Characters] Reveal the top 4 cards of your Library and put them in the Waiting Room. For each Climax card revealed this way, search your Library for up to 1 ::Strange:: Character, reveal it, and put it in your hand. Shuffle your Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi Hachikuji, Lost Cow",
            CardNameJp: "迷い牛 八九寺真宵",
            CardNo: "BM/S15-005",
            Rarity: "R",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "4000",
            Soul: "1",
            Traits: ["Strange", "Spirit"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] When this is placed from hand to the Stage, reveal the top card of your Library. If it's a Climax card, return this to the Library, then shuffle your Library. (Otherwise put the revealed card back where it was)"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi Hachikuji, Lost Cow",
            CardNameJp: "迷い牛 八九寺真宵",
            CardNo: "BM/S15-005R",
            Rarity: "RRR",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "4000",
            Soul: "1",
            Traits: ["Strange", "Spirit"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] When this is placed from hand to the Stage, reveal the top card of your Library. If it's a Climax card, return this to the Library, then shuffle your Library. (Otherwise put the revealed card back where it was)"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi Hachikuji, Lost Snail Girl",
            CardNameJp: "蝸牛に迷った少女 八九寺真宵",
            CardNo: "BM/S15-006",
            Rarity: "R",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "5500",
            Soul: "1",
            Traits: ["Strange", "Spirit"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[C] EXPERIENCE If the sum of Levels of cards in your Level Zone is 2 or higher, this gains +500 Power and \"[A] ENCORE [Discard a Character card from hand to the Waiting Room]\"."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi Hachikuji, Lost Snail Girl",
            CardNameJp: "蝸牛に迷った少女 八九寺真宵",
            CardNo: "BM/S15-006SP",
            Rarity: "SP",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "5500",
            Soul: "1",
            Traits: ["Strange", "Spirit"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[C] EXPERIENCE If the sum of Levels of cards in your Level Zone is 2 or higher, this gains +500 Power and \"[A] ENCORE [Discard a Character card from hand to the Waiting Room]\"."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Shinobu Oshino, Vampire",
            CardNameJp: "吸血鬼の忍野忍",
            CardNo: "BM/S15-007",
            Rarity: "R",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "8000",
            Soul: "2",
            Traits: ["Strange", "Blood"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[C] This gains +1000 Power during your turn. [C] Your Opponent may not use BACKUP from hand during battles involving this."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku, Maniac Girl",
            CardNameJp: "マニアックな子 千石撫子",
            CardNo: "BM/S15-008",
            Rarity: "U",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "Hmm... there are sudden movements. Nya~n",
            Effect: "[A] [Put the top card of your Library in your Clock] When this is placed from the Stage to the Waiting Room, you may pay cost. If so, choose a card in your Level Zone and a card in your Waiting Room. Swap them."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Shinobu Oshino, End of A Vampire",
            CardNameJp: "吸血鬼の成れの果て 忍野忍",
            CardNo: "BM/S15-009",
            Rarity: "U",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Strange", "Blood"],
            Triggers: "None",
            Flavor: "\"End of a vampire is just a pretty ghost's remains. There's nothing that can be done, no?\"",
            Effect: "[A] ENCORE [Discard a Character card from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku, Shy Girl",
            CardNameJp: "内気な少女 千石撫子",
            CardNo: "BM/S15-010",
            Rarity: "U",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "2000",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] When you use the BACKUP of this, choose 1 of your battling YELLOW Characters. That Character gains +1000 Power for the turn. [S] [Counter] BACKUP 1000, Level 1 [Discard this card from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi Hachikuji, Looking Down at Koyomi",
            CardNameJp: "暦を見下す八九寺真宵",
            CardNo: "BM/S15-011",
            Rarity: "U",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "4500",
            Soul: "1",
            Traits: ["Strange", "Spirit"],
            Triggers: "None",
            Flavor: "Koyomi... sounds like a girl's name",
            Effect: "[A] CHANGE [(3) Put this in the Waiting Room] At the beginning of your Encore Step, if this is Rested, you may pay cost. If so, choose a \"Mayoi Hachikuji, Floating Spirit\" in your Waiting Room and put it in the Slot this was in."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi Hachikuji, Floating Spirit",
            CardNameJp: "浮遊霊 八九寺真宵",
            CardNo: "BM/S15-012",
            Rarity: "U",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "8500",
            Soul: "2",
            Traits: ["Strange", "Spirit"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[A] [(2)] When this attacks, if \"Mayoi All the Time\" is in the Climax Zone, you may pay cost. If so, all your Characters gain \"[A] This ability may be primed up to once per turn. When damage dealt by this is Damage Cancelled, you may deal 1 damage to the Opponent\" for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "\"Didn't Mean to\" Mayoi Hachikuji",
            CardNameJp: "“わざとじゃない”八九寺真宵",
            CardNo: "BM/S15-013",
            Rarity: "C",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "500",
            Soul: "1",
            Traits: ["Strange", "Spirit"],
            Triggers: "None",
            Flavor: "Sorry. I did bite you",
            Effect: "[C] ASSIST All your Characters in front of this gain +500 Power. [S] [(2)] Choose 1 of your Opponent's Level 0 or lower Character and return it to the hand."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Shinobu Oshino, Human-Like Vampire",
            CardNameJp: "人間もどきの吸血鬼 忍野忍",
            CardNo: "BM/S15-014",
            Rarity: "C",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "500",
            Soul: "1",
            Traits: ["Strange", "Blood"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] BOND/\"Koyomi Araragi, Vampire-Like Human\" [(1)] [S] [(1)] Choose 1 of your ::Strange:: Characters. That Character gains +500 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku, One-Way Crush",
            CardNameJp: "一途な想い 千石撫子",
            CardNo: "BM/S15-015",
            Rarity: "C",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3000",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Koyomi Araragi, Vampire-Like Human",
            CardNameJp: "吸血鬼もどきの人間 阿良々木暦",
            CardNo: "BM/S15-016",
            Rarity: "C",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "4000",
            Soul: "1",
            Traits: ["Strange", "Blood"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] If you have another Character with \"Shinobu\" in the name, this gains +1500 Power. [A] ENCORE [Discard a Character card from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Shinobu Oshino",
            CardNameJp: "忍野忍",
            CardNo: "BM/S15-017",
            Rarity: "C",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5000",
            Soul: "1",
            Traits: ["Strange", "Blood"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] [Put a Character from your Stage to the Waiting Room] When this attacks, if \"Means to Remain Existing\" is in the Climax Zone, you may pay cost. If so, this gains +4000 Power and +1 Soul for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Shinobu Oshino, Donuts Lover",
            CardNameJp: "ドーナツ好き 忍野忍",
            CardNo: "BM/S15-018",
            Rarity: "C",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "7000",
            Soul: "1",
            Traits: ["Strange", "Blood"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi Hachikuji, Hungry",
            CardNameJp: "腹ペコ 八九寺真宵",
            CardNo: "BM/S15-019",
            Rarity: "C",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "7500",
            Soul: "1",
            Traits: ["Strange", "Spirit"],
            Triggers: "Soul",
            Flavor: "Anyway, Araragi-san, I'm hungry",
            Effect: "[A] [(1)] When this is placed from hand to the Stage, you may pay cost. If so, choose 1 of your Characters. That Character gains +1 Soul for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Shinobu Oshino, Claims to be 500 Years Old",
            CardNameJp: "自称500歳 忍野忍",
            CardNo: "BM/S15-020",
            Rarity: "C",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "8000",
            Soul: "1",
            Traits: ["Strange", "Blood"],
            Triggers: "Soul",
            Flavor: "\"Those that used Hanekawa's stress have been destroyed by Shinobu's energy drain\"",
            Effect: "[C] If there are 5 or more cards in your Stock, this gains +1000 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Actually Fighting",
            CardNameJp: "本気でケンカ",
            CardNo: "BM/S15-021",
            Rarity: "U",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Event",
            Level: "2",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "None",
            Flavor: "\"A male high school student appears to be worried about his life after having punched an elementary school-aged girl twice to knock her unconscious\"",
            Effect: "All your Characters gain +1 Soul for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Fast Talking",
            CardNameJp: "早口言葉",
            CardNo: "BM/S15-022",
            Rarity: "U",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Event",
            Level: "2",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "None",
            Flavor: "Let's see you say \"Nama mumi, nama mome, nama mamamo\" three times fast",
            Effect: "Search your Library for up to 1 ::Strange:: Character, reveal it, and put it in your hand. Shuffle your Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Means to Remain Existing",
            CardNameJp: "存在を保つため",
            CardNo: "BM/S15-023",
            Rarity: "CR",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "Soul Bounce",
            Flavor: "-- None --",
            Effect: "[C] All your Characters gain +1000 Power and +1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi All the Time",
            CardNameJp: "まよいマイマイ",
            CardNo: "BM/S15-024",
            Rarity: "CC",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "Soul Shot",
            Flavor: "-- None --",
            Effect: "[C] All your Characters gain +1000 Power and +1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "A Girl Cursed",
            CardNameJp: "呪いをかけられた少女",
            CardNo: "BM/S15-025",
            Rarity: "CC",
            Color: "Yellow",
            Side: "Schwarz",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "2 Soul",
            Flavor: "-- None --",
            Effect: "[A] When this is placed from hand to the Climax Zone, put the top card of your Library to your Stock, and all your Characters gain +1 Soul for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Tsubasa Hanekawa, Family Issues",
            CardNameJp: "家庭の事情 羽川翼",
            CardNo: "BM/S15-026",
            Rarity: "RR",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "2500",
            Soul: "1",
            Traits: ["Strange", "Chairman"],
            Triggers: "Soul",
            Flavor: "It's the precious Golden Week, wanna study?",
            Effect: "[C] All your other ::Strange:: Characters gain +500 Power and \"[S] [Rest 1 of your Characters] This gains +1000 Power for the turn\". [A] [(1) Put this in the Waiting Room] When \"Secret Rewards\" is placed to your Climax Zone, you may pay cost. If so, choose an '\"Energy Drain\" Black Hanekawa' in your Waiting Room and put it in the Slot this was in."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruga Kanbaru, Girl Wished upon a Monkey",
            CardNameJp: "猿に願った少女 神原駿河",
            CardNo: "BM/S15-027",
            Rarity: "RR",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "8500",
            Soul: "2",
            Traits: ["Strange", "Sports"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[A] [(1)] When \"Suruga Monkey\" is placed to your Climax Zone, if this is in the Front Row, you may pay cost. If so, search your Library for up to 2 Characters with different names and reveal them to your Opponent. Your Opponent choose 1 of them and put it in your Waiting Room, then put the other in your hand. Shuffle your Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruga Kanbaru, Girl Wished upon a Monkey",
            CardNameJp: "猿に願った少女 神原駿河",
            CardNo: "BM/S15-027SP",
            Rarity: "SP",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "8500",
            Soul: "2",
            Traits: ["Strange", "Sports"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[A] [(1)] When \"Suruga Monkey\" is placed to your Climax Zone, if this is in the Front Row, you may pay cost. If so, search your Library for up to 2 Characters with different names and reveal them to your Opponent. Your Opponent choose 1 of them and put it in your Waiting Room, then put the other in your hand. Shuffle your Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruga Kanbaru",
            CardNameJp: "ふっ切れた神原駿河",
            CardNo: "BM/S15-028",
            Rarity: "R",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "1000",
            Soul: "1",
            Traits: ["Strange", "Sports"],
            Triggers: "None",
            Flavor: "Good morning, Araragi Senpai",
            Effect: "[C] EXPERIENCE If the sum of Levels of cards in your Level Zone is 6 or higher, Character opposite this gets -1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Off Day",
            CardNameJp: "休日の戦場ヶ原ひたぎ",
            CardNo: "BM/S15-029",
            Rarity: "R",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "Just think of it like how Araragi-kun can distinguish girls based on their waist shape",
            Effect: "[A] When this is placed from hand to the Stage, put the top card of your Library in your Waiting Room. If it's not a ::Strange:: Character, discard a card from your hand to the Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Off Day",
            CardNameJp: "休日の戦場ヶ原ひたぎ",
            CardNo: "BM/S15-029S",
            Rarity: "SR",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "Just think of it like how Araragi-kun can distinguish girls based on their waist shape",
            Effect: "[A] When this is placed from hand to the Stage, put the top card of your Library in your Waiting Room. If it's not a ::Strange:: Character, discard a card from your hand to the Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Malicious Talker",
            CardNameJp: "毒舌家 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-030",
            Rarity: "R",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5000",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] [Put the top card of your Library in your Clock] When this attacks, if \"Girl Without Weight\" is in the Climax Zone, you may pay cost. If so, all your Characters gain +1 Level and +2000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Koyomi's Lover",
            CardNameJp: "暦の恋人 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-031",
            Rarity: "R",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "6500",
            Soul: "2",
            Traits: ["Strange", "Stationery"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[C] EXPERIENCE This gains +X Power, where X = 500 times the sum of Levels of cards in your Level Zone."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Koyomi's Lover",
            CardNameJp: "暦の恋人 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-031R",
            Rarity: "RRR",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "6500",
            Soul: "2",
            Traits: ["Strange", "Stationery"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[C] EXPERIENCE This gains +X Power, where X = 500 times the sum of Levels of cards in your Level Zone."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruga Kanbaru",
            CardNameJp: "神原駿河",
            CardNo: "BM/S15-032",
            Rarity: "R",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "9500",
            Soul: "2",
            Traits: ["Strange", "Sports"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[C] EXPERIENCE If the sum of Levels of cards in your Level Zone is 5 or higher, this gains +1000 Power and \"[A] ENCORE [Discard a Character card from hand to the Waiting Room]\" [A] When this is placed from hand to the Stage, you may put the top card of your Clock in your Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruga Kanbaru",
            CardNameJp: "神原駿河",
            CardNo: "BM/S15-032S",
            Rarity: "SR",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "9500",
            Soul: "2",
            Traits: ["Strange", "Sports"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[C] EXPERIENCE If the sum of Levels of cards in your Level Zone is 5 or higher, this gains +1000 Power and \"[A] ENCORE [Discard a Character card from hand to the Waiting Room]\" [A] When this is placed from hand to the Stage, you may put the top card of your Clock in your Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruga Hanbaru, Monkey Hands?",
            CardNameJp: "猿の手？ 神原駿河",
            CardNo: "BM/S15-033",
            Rarity: "U",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "500",
            Soul: "1",
            Traits: ["Strange", "Sports"],
            Triggers: "None",
            Flavor: "Correctly converse about the truth without knowing anything... impossible...",
            Effect: "[A] When this attacks, choose 1 of your other ::Strange:: Characters. That Character gains +500 Power for the turn. [A] BOND/\"Hitagi Senjougahara, Malicious Talker\" [(1)]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruga Kanbaru, True to Self",
            CardNameJp: "自分に正直 神原駿河",
            CardNo: "BM/S15-034",
            Rarity: "U",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5000",
            Soul: "1",
            Traits: ["Strange", "Sports"],
            Triggers: "None",
            Flavor: "Hmm? Ah, is that so. Araragi-senpai has no knowledge of BL. I'm surprised",
            Effect: "[C] If this is in the Front Row Center Slot, this gains +1000 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Dating",
            CardNameJp: "デート中 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-035",
            Rarity: "U",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "1000",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[A] CHANGE [(2) Put this in the Waiting Room] At the beginning of your Encore Step, if this is Rested, you may pay cost. If so, choose a \"Hitagi Senjougahara, Koyomi's Lover\" in your Waiting Room and put it in the Slot this was in. [S] [Counter] BACKUP 2000, Level 1 [(1) Discard this card from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Koyomi Araragi, Hates Mornings",
            CardNameJp: "朝が苦手 阿良々木暦",
            CardNo: "BM/S15-036",
            Rarity: "U",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "7500",
            Soul: "1",
            Traits: ["Strange", "Blood"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] If none of your Characters have either \"Karen\" or \"Tsukihi\" in the name, this does not Stand during your Stand Phase."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Forceful",
            CardNameJp: "強引な戦場ヶ原ひたぎ",
            CardNo: "BM/S15-037",
            Rarity: "U",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "5000",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "Soul",
            Flavor: "Let's date",
            Effect: "[C] ASSIST All your Characters in front of this gain +X Power, where X = 500 times Level of that Character. [S] [(1) Rest this] Choose 1 of your Characters. That Character gains +1000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Tsubasa Hanekawa, Knowledgeable",
            CardNameJp: "博覧強記 羽川翼",
            CardNo: "BM/S15-038",
            Rarity: "C",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2000",
            Soul: "1",
            Traits: ["Strange", "Chairman"],
            Triggers: "None",
            Flavor: "I don't know everything. Only things that I know.",
            Effect: "[S] [(1) Rest this] Choose 1 of your ::Strange:: Characters. That Character gains +1500 Power until the end of your Opponent's next turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruga Kanbaru, Former Ace of the Basketball Club",
            CardNameJp: "元バスケ部のエース 神原駿河",
            CardNo: "BM/S15-039",
            Rarity: "C",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2000",
            Soul: "1",
            Traits: ["Strange", "Sports"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] When this attacks, you may choose a Climax in your Climax Zone and put it in your Stock."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruga Kanbaru, Good with Girls",
            CardNameJp: "女性に強い神原駿河",
            CardNo: "BM/S15-040",
            Rarity: "C",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2000",
            Soul: "1",
            Traits: ["Strange", "Sports"],
            Triggers: "None",
            Flavor: "It's true that I'm strong with girls younger than me",
            Effect: "[S] [Rest 1 of your Characters] This gains +1000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Koyomi Araragi, Protagonist Who Helps Everyone",
            CardNameJp: "誰でも助ける主人公 阿良々木暦",
            CardNo: "BM/S15-041",
            Rarity: "C",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Strange", "Blood"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] If there are 5 or more cards in your Stock, all your other ::Strange:: Characters gain +500 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Good with Voice Impersonation",
            CardNameJp: "声色が上手？ 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-042",
            Rarity: "C",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3000",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "I can definitely imitate Araragi-kun, so it'll be fine, let me",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruga Kanbaru, Extremely Truthful",
            CardNameJp: "とっても誠実 神原駿河",
            CardNo: "BM/S15-043",
            Rarity: "C",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5500",
            Soul: "1",
            Traits: ["Strange", "Sports"],
            Triggers: "None",
            Flavor: "I came to apologize for last night",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Tsubasa Hanekawa, Well Conducted",
            CardNameJp: "品行方正 羽川翼",
            CardNo: "BM/S15-044",
            Rarity: "C",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "2500",
            Soul: "1",
            Traits: ["Strange", "Chairman"],
            Triggers: "Soul",
            Flavor: "That's not what I meant when I said \"Kanbaru-san must be troublesome\"",
            Effect: "[S] [Counter] BACKUP 3000, Level 2 [(1) Discard this card from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Tsubasa Hanekawa, Chairman Amongst Chairmans",
            CardNameJp: "委員長の中の委員長 羽川翼",
            CardNo: "BM/S15-045",
            Rarity: "C",
            Color: "Green",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "8500",
            Soul: "1",
            Traits: ["Strange", "Chairman"],
            Triggers: "Soul",
            Flavor: "Hmm? Araraki-kun, still here?",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Stalking",
            CardNameJp: "ストーキング",
            CardNo: "BM/S15-046",
            Rarity: "U",
            Color: "Green",
            Side: "Schwarz",
            Type: "Event",
            Level: "2",
            Cost: "1",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[Counter] Choose up to 2 of your ::Strange:: Characters. Those Characters gain +2000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Rainy Devil",
            CardNameJp: "レイニー・デヴィル",
            CardNo: "BM/S15-047",
            Rarity: "U",
            Color: "Green",
            Side: "Schwarz",
            Type: "Event",
            Level: "2",
            Cost: "1",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "Choose up to 1 of your Opponent's Characters. That Character gets -3000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruga Monkey",
            CardNameJp: "するがモンキー",
            CardNo: "BM/S15-048",
            Rarity: "CR",
            Color: "Green",
            Side: "Schwarz",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "Treasure",
            Flavor: "\"Sorry to have kept you waiting for so long\"",
            Effect: "[C] All your Characters gain +1000 Power and +1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Girl Without Weight",
            CardNameJp: "重さの無い少女",
            CardNo: "BM/S15-049",
            Rarity: "CC",
            Color: "Green",
            Side: "Schwarz",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "2 Soul",
            Flavor: "-- None --",
            Effect: "[A] When this is placed from hand to the Climax Zone, put the top card of your Library to your Stock, and all your Characters gain +1 Soul for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Secret Rewards",
            CardNameJp: "秘密のご褒美",
            CardNo: "BM/S15-050",
            Rarity: "CC",
            Color: "Green",
            Side: "Schwarz",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "Stock",
            Flavor: "Okay, here",
            Effect: "[C] All your Characters gain +1000 Power and +1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi, Girl with Pigtails",
            CardNameJp: "ツインテイルの少女 八九寺真宵",
            CardNo: "BM/S15-051",
            Rarity: "RR",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "4500",
            Soul: "1",
            Traits: ["Strange", "Spirit"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] When this attacks, if \"Girl That Bites\" is in the Climax Zone, this gains +6000 Power for the turn. Then, at the beginning of the Encore Step, return this to your Library, then shuffle your Library. [A] EXPERIENCE When a Level 1 or higher Battle Opponent of this becomes Reversed, if the sum of Levels of cards in your Level Zone is 2 or higher, you may put it on top of the Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi, Girl with Pigtails",
            CardNameJp: "ツインテイルの少女 八九寺真宵",
            CardNo: "BM/S15-051S",
            Rarity: "SR",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "4500",
            Soul: "1",
            Traits: ["Strange", "Spirit"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] When this attacks, if \"Girl That Bites\" is in the Climax Zone, this gains +6000 Power for the turn. Then, at the beginning of the Encore Step, return this to your Library, then shuffle your Library. [A] EXPERIENCE When a Level 1 or higher Battle Opponent of this becomes Reversed, if the sum of Levels of cards in your Level Zone is 2 or higher, you may put it on top of the Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi, Girl Who Encountered a Crab",
            CardNameJp: "蟹に行き遭った少女 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-052",
            Rarity: "RR",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Strange", "Stationery"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[C] EXPERIENCE If the sum of Levels of cards in your Level Zone is 6 or higher, this gains +500 Power and \"[A] [(1)] When a Level 2 or higher Battle Opponent of this becomes Reversed, you may pay cost. If so, choose an Opponent's Character whose Level is 1 or lower and put it in the Waiting Room\". [A] When this is placed from hand to the Stage, you may put the top card of your Clock in your Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi, Girl Who Encountered a Crab",
            CardNameJp: "蟹に行き遭った少女 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-052SP",
            Rarity: "SP",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Strange", "Stationery"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[C] EXPERIENCE If the sum of Levels of cards in your Level Zone is 6 or higher, this gains +500 Power and \"[A] [(1)] When a Level 2 or higher Battle Opponent of this becomes Reversed, you may pay cost. If so, choose an Opponent's Character whose Level is 1 or lower and put it in the Waiting Room\". [A] When this is placed from hand to the Stage, you may put the top card of your Clock in your Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Koyomi Araragi, Tsukkomi",
            CardNameJp: "ツッコミ役 阿良々木暦",
            CardNo: "BM/S15-053",
            Rarity: "R",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "1500",
            Soul: "1",
            Traits: ["Strange", "Blood"],
            Triggers: "None",
            Flavor: "No, I did it on purpose...",
            Effect: "[C] If you are Level 2 or higher, this gains \"[S] [(3) Put the top card of your Library in your Clock] Choose a 'Hitagi, Girl Who Encountered a Crab' in your hand and put it in any Slot on the Stage\". [C] All your other Characters with \"Hitagi\" in the name gains +500 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi Kachikuji, Large Knapsack",
            CardNameJp: "大きなリュックサック 八九寺真宵",
            CardNo: "BM/S15-054",
            Rarity: "R",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "1500",
            Soul: "1",
            Traits: ["Strange", "Spirit"],
            Triggers: "None",
            Flavor: "Anyone would turn around if they got hit from behind!",
            Effect: "[A] When this attacks, choose 1 of your other Characters. That Character gains +500 Power for the turn. [A] When this becomes Reversed, if its Battle Opponent is Level 0 or lower, you may Reverse that Character."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Hollow Girl",
            CardNameJp: "儚げな少女 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-055",
            Rarity: "R",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Strange", "Stationery"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] If you have no other Characters, this gains +1500 Power and \"[A] ENCORE [Discard a Character card from hand to the Waiting Room]\"."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Hollow Girl",
            CardNameJp: "儚げな少女 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-055R",
            Rarity: "RRR",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Strange", "Stationery"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] If you have no other Characters, this gains +1500 Power and \"[A] ENCORE [Discard a Character card from hand to the Waiting Room]\"."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruga Kanbaru, Devil's Left Hand",
            CardNameJp: "悪魔の左手 神原駿河",
            CardNo: "BM/S15-056",
            Rarity: "R",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "7000",
            Soul: "1",
            Traits: ["Strange", "Sports"],
            Triggers: "Soul",
            Flavor: "Everything is half-assed",
            Effect: "[C] If you have another Character with \"Hitagi\", this gains +1500 Power. [A] [(1)] When this attacks, if \"While the Devil Is Gone\" is in the Climax Zone, you may pay cost. If so, deal 1 damage to your Opponent. (Damage Cancel can occur)"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Completely Armored",
            CardNameJp: "完全武装 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-057",
            Rarity: "R",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "7500",
            Soul: "2",
            Traits: ["Strange", "Stationery"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[C] For every other ::Strange:: Character you have, this gains +500 Power. [A] When this attacks, if \"Hitagi Crab\" is in the Climax Zone, you may choose a Character in your Waiting Room and return it to your hand."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Completely Armored",
            CardNameJp: "完全武装 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-057S",
            Rarity: "SR",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "7500",
            Soul: "2",
            Traits: ["Strange", "Stationery"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[C] For every other ::Strange:: Character you have, this gains +500 Power. [A] When this attacks, if \"Hitagi Club\" is in the Climax Zone, you may choose a Character in your Waiting Room and return it to your hand."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Tsukihi Araragi",
            CardNameJp: "阿良々木月火",
            CardNo: "BM/S15-058",
            Rarity: "U",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "500",
            Soul: "1",
            Traits: ["Yukata", "Tea"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] ASSIST All your Characters in front of this gain +500 Power. [S] [(2) Rest this] Search your Library for a Character with \"Koyomi\" in the name, reveal it, and put it in your hand. Shuffle your Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, True Feelings",
            CardNameJp: "素直な気持ち 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-059",
            Rarity: "U",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] All your other \"Koyomi Araragi, Answer to Proposal\" gains +1000 Power. [A] BOND/\"Koyomi Araragi, Answer to Proposal\" [(1)]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruga Kanbaru, Sports Girl",
            CardNameJp: "スポーツ少女 神原駿河",
            CardNo: "BM/S15-060",
            Rarity: "U",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "4500",
            Soul: "1",
            Traits: ["Strange", "Sports"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] CHANGE [(2) Put this in the Waiting Room] At the beginning of your Encore Step, if this is Rested, you may pay cost. If so, choose a \"Suruga Kanbaru, Devil's Left Hand\" in your Waiting Room and put it in the Slot this was in."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Battle Situation",
            CardNameJp: "戦闘態勢 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-061",
            Rarity: "U",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5000",
            Soul: "1",
            Traits: ["Strange", "Stationery"],
            Triggers: "None",
            Flavor: "No, that's wrong --- \"You can move, but it's extremely dangerous\" is more appropriate",
            Effect: "[S] [(1)] This gains +1000 Power and \"[A] When the Battle Opponent of this Character Reverses, you may put the Battle Opponent on top of its owner's Library\" for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Karen Araragi",
            CardNameJp: "阿良々木火憐",
            CardNo: "BM/S15-062",
            Rarity: "U",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "6000",
            Soul: "1",
            Traits: ["Sports", ""],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] ENCORE [Discard a Character card from hand to the Waiting Room] [S] [(2)] This gains +5000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Karen Araragi & Tsukihi Araragi",
            CardNameJp: "阿良々木火憐＆阿良々木月火",
            CardNo: "BM/S15-063",
            Rarity: "C",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Sports", "Yukata"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] [(2)] When this is placed from the Stage to the Waiting Room, you may pay cost. If you do, choose up to 1 ::Strange:: Character in your Waiting Room and return it to your hand."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruka Kanbaru in Casual Clothing",
            CardNameJp: "私服の神原駿河",
            CardNo: "BM/S15-064",
            Rarity: "C",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3000",
            Soul: "1",
            Traits: ["Strange", "Sports"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi Hachikuji, Well-Acquainted",
            CardNameJp: "人見知り 八九寺真宵",
            CardNo: "BM/S15-065",
            Rarity: "C",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "2000",
            Soul: "1",
            Traits: ["Strange", "Spirit"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[S] [Counter] BACKUP 2000, Level 1 [(1) Discard this from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Weightless Girl",
            CardNameJp: "重みを無くした少女 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-066",
            Rarity: "C",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "7000",
            Soul: "1",
            Traits: ["Strange", "Stationery"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara in Casual Clothing",
            CardNameJp: "私服の戦場ヶ原ひたぎ",
            CardNo: "BM/S15-067",
            Rarity: "C",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "8000",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[A] When your other ::Strange:: Character attacks, this gains +1000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi Hachikuji, Elementary School Student",
            CardNameJp: "小学生 八九寺真宵",
            CardNo: "BM/S15-068",
            Rarity: "C",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "8000",
            Soul: "1",
            Traits: ["Strange", "Spirit"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[C] If you have 2 or more other ::Strange:: Characters, this gains +1000 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Koyomi Araragi, Answer to Proposal",
            CardNameJp: "告白の返事 阿良々木暦",
            CardNo: "BM/S15-069",
            Rarity: "C",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "8500",
            Soul: "1",
            Traits: ["Strange", "Blood"],
            Triggers: "Soul",
            Flavor: "The thing about me seeing things that others don't and not seeing things that others do are done. If something's amiss, we'll talk again",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruga Kanbaru, BL-Lover",
            CardNameJp: "BL大好き 神原駿河",
            CardNo: "BM/S15-070",
            Rarity: "C",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "8000",
            Soul: "2",
            Traits: ["Strange", "Sports"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[A] ENCORE [Discard a Character card from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Ritual of Waking up",
            CardNameJp: "目覚めの儀式",
            CardNo: "BM/S15-071",
            Rarity: "U",
            Color: "Red",
            Side: "Schwarz",
            Type: "Event",
            Level: "1",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "All players return all cards in their Waiting Room to their Library. Shuffle those Libraries."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Tsundere?",
            CardNameJp: "ツンデレ？",
            CardNo: "BM/S15-072",
            Rarity: "U",
            Color: "Red",
            Side: "Schwarz",
            Type: "Event",
            Level: "2",
            Cost: "2",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "None",
            Flavor: "What about that girl, Araragi-kun",
            Effect: "Choose up to 2 Characters in your Waiting Room and return them to your hand."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Crab",
            CardNameJp: "ひたぎクラブ",
            CardNo: "BM/S15-073",
            Rarity: "CR",
            Color: "Red",
            Side: "Schwarz",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "Salvage",
            Flavor: "\"Senjougahara and her weight can be best described as nothing\"",
            Effect: "[C] All your Characters gain +1000 Power and +1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Girl That Bites",
            CardNameJp: "噛み噛みの少女",
            CardNo: "BM/S15-074",
            Rarity: "CC",
            Color: "Red",
            Side: "Schwarz",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "2 Soul",
            Flavor: "Full of bite marks",
            Effect: "[A] When this is placed from hand to the Climax Zone, put the top card of your Library to your Stock, and all your Characters gain +1 Soul for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "While the Devil Is Gone",
            CardNameJp: "悪魔が去ったのち",
            CardNo: "BM/S15-075",
            Rarity: "CC",
            Color: "Red",
            Side: "Schwarz",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "2 Soul",
            Flavor: "Even though the devil's gone, my wrist still didn't go back to normal",
            Effect: "[A] When this is placed from hand to the Climax Zone, draw a card, and choose 1 of your Characters. That Character gains +2000 Power and +1 Soul for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Tsubasa Hanekawa, Cat-Enchanted Girl",
            CardNameJp: "猫に魅せられた少女 羽川翼",
            CardNo: "BM/S15-076",
            Rarity: "RR",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "6500",
            Soul: "2",
            Traits: ["Strange", "Chairman"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[C] ASSIST All your ::Strange:: Characters in front of this gain +2000 Power and \"[A] [(1)] When the Battle Opponent of this becomes Reversed, you may pay cost. If so, put that Character on the bottom of the Library\". [A] When this is placed from hand to the Stage, draw up to 2 cards, and discard a card from hand to the Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Tsubasa Hanekawa, Cat-Enchanted Girl",
            CardNameJp: "猫に魅せられた少女 羽川翼",
            CardNo: "BM/S15-076SP",
            Rarity: "SP",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "6500",
            Soul: "2",
            Traits: ["Strange", "Chairman"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[C] ASSIST All your ::Strange:: Characters in front of this gain +2000 Power and \"[A] [(1)] When the Battle Opponent of this becomes Reversed, you may pay cost. If so, put that Character on the bottom of the Library\". [A] When this is placed from hand to the Stage, draw up to 2 cards, and discard a card from hand to the Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku, Snake-Coiled Girl",
            CardNameJp: "蛇に巻きつかれた少女 千石撫子",
            CardNo: "BM/S15-077",
            Rarity: "RR",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Strange", ""],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[A] When this is placed from hand to the Stage or placed via CHANGE to the Stage, you may put the top card of your Clock in your Waiting Room. [A] When this attacks, if \"Nadeko Snake\" is in the Climax Zone, you may pay cost. If so, search your Library for up to 2 \"Nadeko Sengoku, Snake-Coiled Girl\", reveal, and put them in hand. Shuffle your Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku, Snake-Coiled Girl",
            CardNameJp: "蛇に巻きつかれた少女 千石撫子",
            CardNo: "BM/S15-077SP",
            Rarity: "SP",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Strange", ""],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[A] When this is placed from hand to the Stage or placed via CHANGE to the Stage, you may put the top card of your Clock in your Waiting Room. [A] When this attacks, if \"Nadeko Snake\" is in the Climax Zone, you may pay cost. If so, search your Library for up to 2 \"Nadeko Sengoku, Snake-Coiled Girl\", reveal, and put them in hand. Shuffle your Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku, Tsukihi-Chan's Classmate",
            CardNameJp: "月火ちゃんの同級生 千石撫子",
            CardNo: "BM/S15-078",
            Rarity: "R",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "Er, excuse...",
            Effect: "[C] ASSIST All your Characters in front of this gain +500 Power. [S] [(1) Rest this] Choose 1 of your Characters. That Character gains \"[A] ENCORE [Discard a Character card from hand to the Waiting Room]\" until the end of your Opponent's next turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku, Tsukihi-Chan's Classmate",
            CardNameJp: "月火ちゃんの同級生 千石撫子",
            CardNo: "BM/S15-078S",
            Rarity: "SR",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "Er, excuse...",
            Effect: "[C] ASSIST All your Characters in front of this gain +500 Power. [S] [(1) Rest this] Choose 1 of your Characters. That Character gains \"[A] ENCORE [Discard a Character card from hand to the Waiting Room]\" until the end of your Opponent's next turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Tsubasa Hanekawa, Inner Feelings",
            CardNameJp: "内なる気持ち 羽川翼",
            CardNo: "BM/S15-079",
            Rarity: "R",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "1000",
            Soul: "1",
            Traits: ["Strange", "Chairman"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] EXPERIENCE [(2)] When you use the BACKUP of this, if the sum of Levels of cards in your Level Zone is 5 or higher, you may pay cost. If so, choose 1 of the battling Characters. That Character gets -1 Soul for the turn. [S] [Counter] BACKUP 1500, Level 1 [Discard this card from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Koyomi Araragi & Hitagi Senjougahara, Lovers",
            CardNameJp: "恋人同士 阿良々木暦＆戦場ヶ原ひたぎ",
            CardNo: "BM/S15-080",
            Rarity: "R",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "4500",
            Soul: "1",
            Traits: ["Strange", "Blood"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] EXPERIENCE If the sum of Levels of cards in your Level Zone is 2 or higher, this gains +500 Power and \"[A] ENCORE [Discard a Character card from hand to the Waiting Room]\". [A] [(1)] When this attacks, if \"My Everything\" is in the Climax Zone, you may pay cost. If so, look at up to the top 5 cards of your Library and choose up to 1 ::Strange:: Character, reveal it, and put it in your hand. Put the other cards in your Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Koyomi Araragi & Hitagi Senjougahara, Lovers",
            CardNameJp: "恋人同士 阿良々木暦＆戦場ヶ原ひたぎ",
            CardNo: "BM/S15-080R",
            Rarity: "RRR",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "4500",
            Soul: "1",
            Traits: ["Strange", "Blood"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] EXPERIENCE If the sum of Levels of cards in your Level Zone is 2 or higher, this gains +500 Power and \"[A] ENCORE [Discard a Character card from hand to the Waiting Room]\". [A] [(1)] When this attacks, if \"My Everything\" is in the Climax Zone, you may pay cost. If so, look at up to the top 5 cards of your Library and choose up to 1 ::Strange:: Character, reveal it, and put it in your hand. Put the other cards in your Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Black Hanekawa",
            CardNameJp: "ブラック羽川",
            CardNo: "BM/S15-081",
            Rarity: "R",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "7500",
            Soul: "2",
            Traits: ["Strange", "Chairman"],
            Triggers: "Soul",
            Flavor: "Nnya?",
            Effect: "[A] When this attacks, if \"Tsubasa Cat\" is in the Climax Zone, search your Library for up to 1 card with the same name as 1 of your Characters on your Stage, reveal it, and put it in your hand. Shuffle your Library. [A] ENCORE [Discard a Character card from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Black Hanekawa",
            CardNameJp: "ブラック羽川",
            CardNo: "BM/S15-081S",
            Rarity: "SR",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "7500",
            Soul: "2",
            Traits: ["Strange", "Chairman"],
            Triggers: "Soul",
            Flavor: "Nnya?",
            Effect: "[A] When this attacks, if \"Tsubasa Cat\" is in the Climax Zone, search your Library for up to 1 card with the same name as 1 of your Characters on your Stage, reveal it, and put it in your hand. Shuffle your Library. [A] ENCORE [Discard a Character card from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku, Rewards for Curse Removal",
            CardNameJp: "解呪のお礼 千石撫子",
            CardNo: "BM/S15-082",
            Rarity: "R",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "8500",
            Soul: "2",
            Traits: ["Strange", ""],
            Triggers: "Soul",
            Flavor: "\"Don't do it, Sengoku. I beg you, please don't say 'thank you'\"",
            Effect: "[A] When this is Front Attacked, put the top card of your Library in your Waiting Room. If it's a ::Strange:: Character, this gains +1000 Power and \"[A] ENCORE [Discard a Character card from hand to the Waiting Room]\" for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku",
            CardNameJp: "千石撫子",
            CardNo: "BM/S15-083",
            Rarity: "U",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "1500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] Another Character in your Front Row Center Slot gains +1000 Power during your Opponent's turn. [S] [(1)] Draw a card, and discard a card from your hand to the Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Meme Oshino",
            CardNameJp: "忍野メメ",
            CardNo: "BM/S15-084",
            Rarity: "U",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] [(1)] When this is placed from hand to the Stage, you may pay cost. If so, choose a card in your Level Zone and a card in your Waiting Room. Swap them."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Tsubasa Hanekawa in Pajamas",
            CardNameJp: "パジャマ姿の羽川翼",
            CardNo: "BM/S15-085",
            Rarity: "U",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Strange", "Chairman"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] When this is placed from hand to the Stage, this gains +X Power, where X = 500 times # of ::Strange:: Characters you have."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Meme Oshino, Authority on Monster Changing",
            CardNameJp: "妖怪変化のオーソリティー 忍野メメ",
            CardNo: "BM/S15-086",
            Rarity: "U",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "3000",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "Haha, is that so, this is that, the rumored person about the founding anniversary",
            Effect: "[C] All your other Characters gain +500 Power during your Opponent's turn. [S] BRAINSTORM [(1)] Reveal the top 2 cards of your Library and put them in the Waiting Room. For each Climax card revealed this way, draw a card."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku, Cursed Girl",
            CardNameJp: "呪いをかけられた少女 千石撫子",
            CardNo: "BM/S15-087",
            Rarity: "U",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "6000",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] This gains +1000 Power during your Opponent's turn. [A] ENCORE [Discard a Character card from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku, Ambushing",
            CardNameJp: "待ち伏せ 千石撫子",
            CardNo: "BM/S15-088",
            Rarity: "U",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "7500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "Soul",
            Flavor: "Ah...... Koyomi onii-chan. I've been waiting for you",
            Effect: "[A] CHANGE [(1) Put this in Clock] At the beginning of your Encore Step, if this is Rested, you may pay cost. If so, choose a \"Nadeko Sengoku, Snake-Coiled Girl\" in your Waiting Room and put it in the Slot this was in."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Koyomi Araragi, Running Around",
            CardNameJp: "奔走する阿良々木暦",
            CardNo: "BM/S15-089",
            Rarity: "C",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "500",
            Soul: "1",
            Traits: ["Strange", "Blood"],
            Triggers: "None",
            Flavor: "Oshino thought of that too...... but we still don't know the source of the stress",
            Effect: "[C] All your other ::Chairman:: Characters gain +500 Power during your Opponent's turn. [A] BOND/\"Tsubasa Hanekawa\" [(1)]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku, Curse Removal Ritual",
            CardNameJp: "解呪の儀式 千石撫子",
            CardNo: "BM/S15-090",
            Rarity: "C",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] This gains +1000 Power during your Opponent's turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Tsubasa Hanekawa, Knowing Everything",
            CardNameJp: "なんでも知ってる羽川翼",
            CardNo: "BM/S15-091",
            Rarity: "C",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Strange", "Chairman"],
            Triggers: "None",
            Flavor: "Oh? I thought this is normal",
            Effect: "[S] [Rest 2 of your Characters] This gains +1000 Power until end of your Opponent's next turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Cat-Eared Tsubasa Hanekawa",
            CardNameJp: "ネコミミ 羽川翼",
            CardNo: "BM/S15-092",
            Rarity: "C",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3000",
            Soul: "1",
            Traits: ["Strange", "Chairman"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku, Girl of Age",
            CardNameJp: "年頃の女の子 千石撫子",
            CardNo: "BM/S15-093",
            Rarity: "C",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "Koyomi nii-san... and Kanbaru-san... Can you turn around for a little bit?",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Tsubasa Hanekawa",
            CardNameJp: "羽川翼",
            CardNo: "BM/S15-094",
            Rarity: "C",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "3500",
            Soul: "1",
            Traits: ["Strange", "Chairman"],
            Triggers: "Soul",
            Flavor: "Araragi-kun's habit is cheeky",
            Effect: "[C] ASSIST All your Level 2 or higher Characters in front of this gain +1000 Power. [C] EXPERIENCE If the sum of Levels of cards in your Level Zone is 4 or higher, this gains \"[C] All your other ::Strange:: Characters gain +500 Power during your Opponent's turn\"."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Meme Oshino, Man Who Sees Through Everything",
            CardNameJp: "見透かした男 忍野メメ",
            CardNo: "BM/S15-095",
            Rarity: "C",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "2500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "Soul",
            Flavor: "I'm so busy that I don't really have time",
            Effect: "[S] [Counter] BACKUP 3000, Level 2 [(1) Discard this card from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "\"Energy Drain\" Black Hanekawa",
            CardNameJp: "“エナジードレイン”ブラック羽川",
            CardNo: "BM/S15-096",
            Rarity: "C",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "9000",
            Soul: "1",
            Traits: ["Strange", "Chairman"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[C] You cannot use \"[A] ENCORE\" on any of your other Characters. (This includes \"[A] ENCORE [(3)]\" provided by the rules)"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Don't Tell Anyone",
            CardNameJp: "みんなには内緒だよ",
            CardNo: "BM/S15-097",
            Rarity: "U",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Event",
            Level: "2",
            Cost: "1",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "Draw up to 2 cards, and discard a card from hand to your Waiting Room. Choose 1 of your ::Strange:: Characters. That Character gains +3000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Snake",
            CardNameJp: "なでこスネイク",
            CardNo: "BM/S15-098",
            Rarity: "CR",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "Draw",
            Flavor: "Look at me, Koyomi onii-chan",
            Effect: "[C] All your Characters gain +1000 Power and +1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "My Everything",
            CardNameJp: "私のすべて",
            CardNo: "BM/S15-099",
            Rarity: "CC",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "2 Soul",
            Flavor: "-- None --",
            Effect: "[C] All your Characters gain +2 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Tsubasa Cat",
            CardNameJp: "つばさキャット",
            CardNo: "BM/S15-100",
            Rarity: "CC",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "2 Soul",
            Flavor: "You're still useless as usual",
            Effect: "[A] When this is placed from hand to the Climax Zone, put the top card of your Library to your Stock, and all your Characters gain +1 Soul for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Koyomi Araragi, Unmoving Taciturnity",
            CardNameJp: "不動の寡黙 阿良々木暦",
            CardNo: "BM/S15-101",
            Rarity: "TD",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5000",
            Soul: "1",
            Traits: ["Strange", "Blood"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] [Return 2 Characters from your Waiting Room to Library, Shuffle your Library] When this attacks, you may pay cost. If so, this gains +2000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Extremely Suspicious",
            CardNameJp: "疑り深い戦場ヶ原ひたぎ",
            CardNo: "BM/S15-102",
            Rarity: "TD",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "6500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "It's nothing. So don't worry",
            Effect: "[A] When this attacks, choose up to 2 of your ::Strange:: Characters. Those Characters gain +500 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Tender-Cared Daughter",
            CardNameJp: "深窓の令嬢 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-103",
            Rarity: "TD",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Strange", "Stationery"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[A] When this is placed from hand to the Stage, you may choose 1 ::Strange:: Character in your Waiting Room and return it to your hand. [S] [Rest 2 of your ::Strange:: Characters] This gains +2500 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Big Crab",
            CardNameJp: "おもし蟹",
            CardNo: "BM/S15-104",
            Rarity: "TD",
            Color: "Red",
            Side: "Schwarz",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "2 Soul",
            Flavor: "Like then, I can see a big, big crab---",
            Effect: "[A] When this is placed from hand to the Climax Zone, draw a card, and choose 1 of your Characters. That Character gains +2000 Power and +1 Soul for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Tsubasa Hanekawa, Ultimate Perfect Student",
            CardNameJp: "究極の優等生 羽川翼",
            CardNo: "BM/S15-105",
            Rarity: "TD",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "1000",
            Soul: "1",
            Traits: ["Strange", "Chairman"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] ASSIST All your Characters in front of this gain +500 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Karen Araragi & Tsukihi Araragi",
            CardNameJp: "阿良々木火憐＆阿良々木月火",
            CardNo: "BM/S15-T01",
            Rarity: "TD",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Sports", "Yukata"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] [(2)] When this is placed from the Stage to the Waiting Room, you may pay cost. If you do, choose up to 1 ::Strange:: Character in your Waiting Room and return it to your hand."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruka Kanbaru in Casual Clothing",
            CardNameJp: "私服の神原駿河",
            CardNo: "BM/S15-T02",
            Rarity: "TD",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3000",
            Soul: "1",
            Traits: ["Strange", "Sports"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Battle Situation",
            CardNameJp: "戦闘態勢 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-T03",
            Rarity: "TD",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5000",
            Soul: "1",
            Traits: ["Strange", "Stationery"],
            Triggers: "None",
            Flavor: "No, that's wrong --- \"You can move, but it's extremely dangerous\" is more appropriate",
            Effect: "[S] [(1)] This gains +1000 Power and \"[A] When the Battle Opponent of this Character Reverses, you may put the Battle Opponent on top of its owner's Library\" for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi Hachikuji, Well-Acquainted",
            CardNameJp: "人見知り 八九寺真宵",
            CardNo: "BM/S15-T04",
            Rarity: "TD",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "2000",
            Soul: "1",
            Traits: ["Strange", "Spirit"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[S] [Counter] BACKUP 2000, Level 1 [(1) Discard this from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara, Weightless Girl",
            CardNameJp: "重みを無くした少女 戦場ヶ原ひたぎ",
            CardNo: "BM/S15-T05",
            Rarity: "TD",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "7000",
            Soul: "1",
            Traits: ["Strange", "Stationery"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Senjougahara in Casual Clothing",
            CardNameJp: "私服の戦場ヶ原ひたぎ",
            CardNo: "BM/S15-T06",
            Rarity: "TD",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "8000",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "Soul",
            Flavor: "No... Uh, I hate to say this, but about that life that you were talking about... I couldn't quite follow it",
            Effect: "[A] When your other ::Strange:: Character attacks, this gains +1000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mayoi Hachikuji, Elementary School Student",
            CardNameJp: "小学生 八九寺真宵",
            CardNo: "BM/S15-T07",
            Rarity: "TD",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "8000",
            Soul: "1",
            Traits: ["Strange", "Spirit"],
            Triggers: "Soul",
            Flavor: "Senjougahara-san is the girlfriend of Araragi-san",
            Effect: "[C] If you have 2 or more other ::Strange:: Characters, this gains +1000 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Suruga Kanbaru, BL-Lover",
            CardNameJp: "BL大好き 神原駿河",
            CardNo: "BM/S15-T08",
            Rarity: "TD",
            Color: "Red",
            Side: "Schwarz",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "8000",
            Soul: "2",
            Traits: ["Strange", "Sports"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[A] ENCORE [Discard a Character card from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitagi Crab",
            CardNameJp: "ひたぎクラブ",
            CardNo: "BM/S15-T09",
            Rarity: "TD",
            Color: "Red",
            Side: "Schwarz",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "Salvage",
            Flavor: "\"Senjougahara and her weight can be best described as nothing\"",
            Effect: "[C] All your Characters gain +1000 Power and +1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku, Curse Removal Ritual",
            CardNameJp: "解呪の儀式 千石撫子",
            CardNo: "BM/S15-T10",
            Rarity: "TD",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] This gains +1000 Power during your Opponent's turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Tsubasa Hanekawa in Pajamas",
            CardNameJp: "パジャマ姿の羽川翼",
            CardNo: "BM/S15-T11",
            Rarity: "TD",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Strange", "Chairman"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] When this is placed from hand to the Stage, this gains +X Power, where X = 500 times # of ::Strange:: Characters you have."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Cat-Eared Tsubasa Hanekawa",
            CardNameJp: "ネコミミ 羽川翼",
            CardNo: "BM/S15-T12",
            Rarity: "TD",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3000",
            Soul: "1",
            Traits: ["Strange", "Chairman"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nadeko Sengoku, Girl of Age",
            CardNameJp: "年頃の女の子 千石撫子",
            CardNo: "BM/S15-T13",
            Rarity: "TD",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5500",
            Soul: "1",
            Traits: ["Strange", ""],
            Triggers: "None",
            Flavor: "Koyomi nii-san... and Kanbaru-san... Can you turn around for a little bit?",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "My Everything",
            CardNameJp: "私のすべて",
            CardNo: "BM/S15-T14",
            Rarity: "TD",
            Color: "Blue",
            Side: "Schwarz",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "2 Soul",
            Flavor: "-- None --",
            Effect: "[C] All your Characters gain +2 Soul."
        });
    };
}(window.gate = window.gate || {}));
