(function(gate, undefined) {
    var cardsetCode = "MM/W17"; // <-- IMPORTANT
    if(gate.cardsets == null) gate.cardsets = [];
    if(gate.cardset == null) gate.cardset = {};
    if($.inArray(cardsetCode, gate.cardsets) == -1) {
        gate.cardsets.push(cardsetCode);
        // Cardset Properties
        gate.cardset[cardsetCode] = {};
        gate.cardset[cardsetCode].SetName = "Madoka Magica";
        gate.cardset[cardsetCode].SetCode = "MM";
        gate.cardset[cardsetCode].SetSide = "W";
        gate.cardset[cardsetCode].SetNum = "17";
        gate.cardset[cardsetCode].Cards = [];
        // Cardset Cards
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami, Silver Magical Gun",
            CardNameJp: "銀の魔銃 マミ",
            CardNo: "MM/W17-001",
            Rarity: "RR",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "7500",
            Soul: "1",
            Traits: ["Magic", "Tea"],
            Triggers: "Soul",
            Flavor: "I'll finish you off with a swift attack today.",
            Effect: "[C] During your turn, if the Level of the Character opposite this is 3 or higher, this gains +4000 Power and +1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami, Silver Magical Gun",
            CardNameJp: "銀の魔銃 マミ",
            CardNo: "MM/W17-001S",
            Rarity: "SR",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "7500",
            Soul: "1",
            Traits: ["Magic", "Tea"],
            Triggers: "Soul",
            Flavor: "SECRET",
            Effect: "[C] During your turn, if the Level of the Character opposite this is 3 or higher, this gains +4000 Power and +1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami Tomoe",
            CardNameJp: "巴 マミ",
            CardNo: "MM/W17-002",
            Rarity: "RR",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Magic", "Tea"],
            Triggers: "Soul",
            Flavor: "I feel bad because this happens rarely, but let's finish this --- now!",
            Effect: "[A] When this is placed from hand to the Stage, you may put the top card of your Clock in the Waitng Room. [A] [(2)] When this attacks, if \"Tiro Finale\" is in the Climax Zone, you may pay cost. If so, choose up to 1 Level 3 or lower Character in your Opponent's Front Row and put it in Stock, and your Opponent may not use Encore for the turn. (This includes \"[A] ENCORE [(3)]\" provided by the rules.)"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami Tomoe",
            CardNameJp: "巴 マミ",
            CardNo: "MM/W17-002SP",
            Rarity: "SP",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Magic", "Tea"],
            Triggers: "Soul",
            Flavor: "SECRET",
            Effect: "[A] When this is placed from hand to the Stage, you may put the top card of your Clock in the Waitng Room. [A] [(2)] When this attacks, if \"Tiro Finale\" is in the Climax Zone, you may pay cost. If so, choose up to 1 Level 3 or lower Character in your Opponent's Front Row and put it in Stock, and your Opponent may not use Encore for the turn. (This includes \"[A] ENCORE [(3)]\" provided by the rules.)"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyubey, Making Contract",
            CardNameJp: "契約をせまるキュゥべえ",
            CardNo: "MM/W17-003",
            Rarity: "R",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "500",
            Soul: "1",
            Traits: ["Alien", "Magic"],
            Triggers: "None",
            Flavor: "Make a contract with me and become a magical girl!",
            Effect: "[C] All your other ::Magic:: Characters gain +500 Power. [C] When you pay for the CHANGE cost of your Characters, you may put a Marker from under this in the Waiting Room in place of 1 Stock. [A] When this is placed from hand to the Stage, put the top card of your Library under this as Marker."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami, Senior Magical Girl",
            CardNameJp: "先輩魔法少女 マミ",
            CardNo: "MM/W17-004",
            Rarity: "R",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "500",
            Soul: "1",
            Traits: ["Magic", "Tea"],
            Triggers: "None",
            Flavor: "Now, magical girls who contracted with Kyubey",
            Effect: "[A] [(2)] When this is placed from hand to the Stage, you may pay cost. If so, search your Library for up to 1 ::Magic:: Character, reveal it, and put it in your hand. Shuffle your Library. [A] [Clock] SHIFT Level 0"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami, Senior Magical Girl",
            CardNameJp: "先輩魔法少女 マミ",
            CardNo: "MM/W17-004S",
            Rarity: "SR",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "500",
            Soul: "1",
            Traits: ["Magic", "Tea"],
            Triggers: "None",
            Flavor: "SECRET",
            Effect: "[A] [(2)] When this is placed from hand to the Stage, you may pay cost. If so, search your Library for up to 1 ::Magic:: Character, reveal it, and put it in your hand. Shuffle your Library. [A] [Clock] SHIFT Level 0"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami in Pajamas",
            CardNameJp: "パジャマのマミ",
            CardNo: "MM/W17-005",
            Rarity: "R",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5000",
            Soul: "1",
            Traits: ["Magic", "Tea"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[A] When this is placed from hand to the Stage, if you have 2 or more other ::Magic:: Characters, this gains +2000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami, Shouldering Fate",
            CardNameJp: "宿命を背負うマミ",
            CardNo: "MM/W17-006",
            Rarity: "R",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "9000",
            Soul: "2",
            Traits: ["Magic", "Tea"],
            Triggers: "Soul",
            Flavor: "For me... I didn't have time to think",
            Effect: "[C] No player may use BACKUP from hand during battles involving this Character."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami, Shouldering Fate",
            CardNameJp: "宿命を背負うマミ",
            CardNo: "MM/W17-006R",
            Rarity: "RRR",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "9000",
            Soul: "2",
            Traits: ["Magic", "Tea"],
            Triggers: "Soul",
            Flavor: "SECRET",
            Effect: "[C] No player may use BACKUP from hand during battles involving this Character."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "\"Dessert Witch\" Charlotte",
            CardNameJp: "“お菓子の魔女”シャルロッテ",
            CardNo: "MM/W17-007",
            Rarity: "U",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3000",
            Soul: "1",
            Traits: ["Magic", "Sweets"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "[C] Character Opposite this gains +1 Soul. [A] During battles involving this card, when damage dealt to you is cancelled, this gains +1000 Power until the end of your next turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "\"No Longer Alone\" Mami",
            CardNameJp: "“もうひとりじゃない”マミ",
            CardNo: "MM/W17-008",
            Rarity: "U",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5000",
            Soul: "1",
            Traits: ["Magic", "Tea"],
            Triggers: "None",
            Flavor: "My body feels light. I've never fought so happily before",
            Effect: "[A] When this Front Attacks, if \"Nothing Scares Me Anymore\" is in the Climax Zone, reveal the top card of your Library. If it's a Climax card, this gets -4500 Power for the turn. Otherwise, this gains +4500 Power for the turn. (Put the revealed card back where it was)"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami, Wish for Survival",
            CardNameJp: "生きるための願い マミ",
            CardNo: "MM/W17-009",
            Rarity: "U",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "2500",
            Soul: "1",
            Traits: ["Magic", "Tea"],
            Triggers: "Soul",
            Flavor: "Being a magical girl... isn't a good thing",
            Effect: "[C] All your other Characters gain +1000 Power during your turn. [A] CHANGE [(1) Put this in the Waiting Room] At the beginning of the Draw Phase, you may pay cost. If so, choose 1 \"Mami, Shouldering Fate\" in your Waiting Room and put it in the Slot this was in."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami, Binding Magic",
            CardNameJp: "束縛魔法 マミ",
            CardNo: "MM/W17-010",
            Rarity: "U",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "2500",
            Soul: "1",
            Traits: ["Magic", "Tea"],
            Triggers: "Soul",
            Flavor: "Akemi-san, please!",
            Effect: "[S] [Counter] BACKUP 3000, Level 2 [(1) Discard this card from hand to your Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami, Enjoying Tea",
            CardNameJp: "お茶をたしなむマミ",
            CardNo: "MM/W17-011",
            Rarity: "C",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "500",
            Soul: "1",
            Traits: ["Magic", "Tea"],
            Triggers: "None",
            Flavor: "That's right, it's risking your life. That's why you all should choose carefully",
            Effect: "[C] ASSIST All your Characters in front of this gain +500 Power. [S] [Rest this] Choose 1 of your Characters with \"Madoka\" in the name. That Character gains +500 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami, Giving Advice",
            CardNameJp: "忠告するマミ",
            CardNo: "MM/W17-012",
            Rarity: "C",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Magic", "Tea"],
            Triggers: "None",
            Flavor: "-- Try not to let this happen to you a second time",
            Effect: "[C] This gains +1000 Power during your turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami, Veteran Magical Girl",
            CardNameJp: "ベテラン魔法少女 マミ",
            CardNo: "MM/W17-013",
            Rarity: "C",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3000",
            Soul: "1",
            Traits: ["Magic", "Tea"],
            Triggers: "None",
            Flavor: "Don't worry. I wouldn't want future newbies see me doing horribly!",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami, Entrusting the Future",
            CardNameJp: "希望を託すマミ",
            CardNo: "MM/W17-014",
            Rarity: "C",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5500",
            Soul: "1",
            Traits: ["Magic", "Tea"],
            Triggers: "None",
            Flavor: "You yourself are hope. All of our hope",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami, Kindly Watching Over",
            CardNameJp: "優しく見守るマミ",
            CardNo: "MM/W17-015",
            Rarity: "C",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "7000",
            Soul: "1",
            Traits: ["Magic", "Tea"],
            Triggers: "None",
            Flavor: "Oops... I tried to act more like your mentor, but that turns out to be something I can't do",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Mami, Graceful",
            CardNameJp: "優雅なるマミ",
            CardNo: "MM/W17-016",
            Rarity: "C",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "8500",
            Soul: "1",
            Traits: ["Magic", "Tea"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Grief Seed",
            CardNameJp: "グリーフシード",
            CardNo: "MM/W17-017",
            Rarity: "U",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Event",
            Level: "2",
            Cost: "1",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "None",
            Flavor: "Mami: \"This is a Grief Seed. An egg of a witch\"",
            Effect: "[Counter] Choose 1 of your Characters. That Characters gains +X Power. X"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sudden Happening",
            CardNameJp: "一瞬の出来事",
            CardNo: "MM/W17-018",
            Rarity: "U",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Event",
            Level: "2",
            Cost: "2",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "None",
            Flavor: "--Eh?",
            Effect: "Choose 1 Level 2 or lower Character in your Opponent's Front Row and Send it to Memory."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Nothing Scares Me Anymore",
            CardNameJp: "もう何も恐くない",
            CardNo: "MM/W17-019",
            Rarity: "CR",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "Soul Bounce",
            Flavor: "-- I am not alone",
            Effect: "[C] All your Characters gain +1000 Power and +1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Tiro Finale",
            CardNameJp: "ティロ・フィナーレ",
            CardNo: "MM/W17-020",
            Rarity: "CC",
            Color: "Yellow",
            Side: "Weiss",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "2 Soul",
            Flavor: "Tiro Fina----le!!",
            Effect: "[A] When this is placed from hand to the Stage, draw a card, and choose 1 of your Characters. That Character gains +2000 Power and +1 Soul for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Tragic Determination",
            CardNameJp: "悲壮な覚悟 ほむら",
            CardNo: "MM/W17-021",
            Rarity: "RR",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "7500",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "Soul",
            Flavor: "This has nothing to do with you",
            Effect: "[A] When this attacks, if \"No Longer Relying on Others\" is in the Climax Zone, and you have no other Standing Character in the Front Row, this gains +7000 Power for the turn. [A] [Clock] SHIFT Level 2"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Tragic Determination",
            CardNameJp: "悲壮な覚悟 ほむら",
            CardNo: "MM/W17-021SP",
            Rarity: "SP",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "7500",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "Soul",
            Flavor: "SECRET",
            Effect: "[A] When this attacks, if \"No Longer Relying on Others\" is in the Climax Zone, and you have no other Standing Character in the Front Row, this gains +7000 Power for the turn. [A] [Clock] SHIFT Level 2"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "\"Secrecy\" Madoka",
            CardNameJp: "“内緒”のまどか",
            CardNo: "MM/W17-022",
            Rarity: "RR",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "7500",
            Soul: "1",
            Traits: ["Magic", ""],
            Triggers: "Soul",
            Flavor: "My secret is out",
            Effect: "[C] If you have 3 or more other ::Magic:: Characters, this gains +1000 Power. [A] When this attacks, if \"Don't Tell Anyone in Class!\" is in the Climax zone, choose up to 1 of your other Characters and Send it to Memory, and at the beginning of your next Draw Phase, put that Character from Memory in any Slot on the Stage. [A] When this attacks, if \"Don't Tell Anyone in Class!\" is in the Climax Zone, this gains +2000 Power until the end of your next turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "\"Secrecy\" Madoka",
            CardNameJp: "“内緒”のまどか",
            CardNo: "MM/W17-022SP",
            Rarity: "SP",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "7500",
            Soul: "1",
            Traits: ["Magic", ""],
            Triggers: "Soul",
            Flavor: "SECRET",
            Effect: "[C] If you have 3 or more other ::Magic:: Characters, this gains +1000 Power. [A] When this attacks, if \"Don't Tell Anyone in Class!\" is in the Climax zone, choose up to 1 of your other Characters and Send it to Memory, and at the beginning of your next Draw Phase, put that Character from Memory in any Slot on the Stage. [A] When this attacks, if \"Don't Tell Anyone in Class!\" is in the Climax Zone, this gains +2000 Power until the end of your next turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Beautiful Looks",
            CardNameJp: "容姿端麗 ほむら",
            CardNo: "MM/W17-023",
            Rarity: "R",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2000",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "None",
            Flavor: "You should just live as Madoka Kaname. Like you have been, and from now on",
            Effect: "[A] [Choose 2 Characters cards in your Waiting Room and return it to your Library. Shuffle your Library] When this is played from hand to the Stage, you may pay cost. If so, this gains +2000 Power for the turn. [A] [Clock] SHIFT Level 0"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Beautiful Looks",
            CardNameJp: "容姿端麗 ほむら",
            CardNo: "MM/W17-023S",
            Rarity: "SR",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2000",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "None",
            Flavor: "SECRET",
            Effect: "[A] [Choose 2 Characters cards in your Waiting Room and return it to your Library. Shuffle your Library] When this is played from hand to the Stage, you may pay cost. If so, this gains +2000 Power for the turn. [A] [Clock] SHIFT Level 0"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Watching Over",
            CardNameJp: "見守るほむら",
            CardNo: "MM/W17-024",
            Rarity: "R",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "None",
            Flavor: "She cannot be allowed to make a contract",
            Effect: "[S] BRAINSTORM [(1) Rest 2 of your Characters] Reveal the top 4 cards of your Library and put it in the Waiting Room. For each Climax card revealed this way, search your Library for up to 1 ::Magic:: Character, reveal it, and put it in your hand. Shuffle your Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Hidden Feelings",
            CardNameJp: "隠された思い ほむら",
            CardNo: "MM/W17-025",
            Rarity: "R",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "6000",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "None",
            Flavor: "I cannot tell her my true feelings",
            Effect: "[C] If you have 2 or fewer ::Magic:: Characters, you cannot play this from hand."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Hidden Feelings",
            CardNameJp: "隠された思い ほむら",
            CardNo: "MM/W17-025S",
            Rarity: "SR",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "6000",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "None",
            Flavor: "SECRET",
            Effect: "[C] If you have 2 or fewer ::Magic:: Characters, you cannot play this from hand."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka, Magical Girl of the Bow",
            CardNameJp: "弓の魔法少女 まどか",
            CardNo: "MM/W17-026",
            Rarity: "R",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "6500",
            Soul: "1",
            Traits: ["Magic", ""],
            Triggers: "None",
            Flavor: "Even then -- I'm a magical girl. I must protect everyone",
            Effect: "[C] If there are 4 or more cards in your Stock, this gains +1000 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka, Magical Girl of the Bow",
            CardNameJp: "弓の魔法少女 まどか",
            CardNo: "MM/W17-026S",
            Rarity: "SR",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "6500",
            Soul: "1",
            Traits: ["Magic", ""],
            Triggers: "None",
            Flavor: "SECRET",
            Effect: "[C] If there are 4 or more cards in your Stock, this gains +1000 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka, Wavering Feelings",
            CardNameJp: "揺れ動く気持ち まどか",
            CardNo: "MM/W17-027",
            Rarity: "R",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "5000",
            Soul: "1",
            Traits: ["Magic", ""],
            Triggers: "Soul",
            Flavor: "... I'm sorry... I'm a weakling... I'm sorry...",
            Effect: "[C] ASSIST All your Characters in front of this gain +X Power. X = 500 times the Level of the Character. [A] CHANGE [(1) Put this in the Waiting Room] At the beginning of your Draw Phase, you may pay cost. If so, choose a \"Madoka, Ultimate\" in your Waiting Room and put it in the Slot this was in."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Magical Girl of Time",
            CardNameJp: "時の魔法少女 ほむら",
            CardNo: "MM/W17-028",
            Rarity: "R",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "8000",
            Soul: "2",
            Traits: ["Magic", "Time"],
            Triggers: "Soul",
            Flavor: "No one will accept the future. Then, I will--",
            Effect: "[C] If there are 5 or more cards in your Stock, this gains +1000 Power. [A] [Discard a ::Magic:: Character card from your hand to the Waiting Room, Send this to Memory] When this becomes Reversed in Battle, you may pay cost. If so, at the beginning of your next Draw Phase, choose 1 \"Homura, Magical Girl of Time\" in your Memory and put it in any Slot on the Stage."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Magical Girl of Time",
            CardNameJp: "時の魔法少女 ほむら",
            CardNo: "MM/W17-028R",
            Rarity: "RRR",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "8000",
            Soul: "2",
            Traits: ["Magic", "Time"],
            Triggers: "Soul",
            Flavor: "SECRET",
            Effect: "[C] If there are 5 or more cards in your Stock, this gains +1000 Power. [A] [Discard a ::Magic:: Character card from your hand to the Waiting Room, Send this to Memory] When this becomes Reversed in Battle, you may pay cost. If so, at the beginning of your next Draw Phase, choose 1 \"Homura, Magical Girl of Time\" in your Memory and put it in any Slot on the Stage."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka, Fate's Final Destination",
            CardNameJp: "因果の終着点 まどか",
            CardNo: "MM/W17-029",
            Rarity: "R",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "8500",
            Soul: "2",
            Traits: ["Magic", ""],
            Triggers: "Soul",
            Flavor: "Kyubey: \"The size of the soul gem that Madoka would produce is unmeasurable even to me\"",
            Effect: "[C] For each Marker under this, this gains +1500 Power. [A] When you Refresh your Library, you may put the top card of your Library under this as a Marker."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka, Fate's Final Destination",
            CardNameJp: "因果の終着点 まどか",
            CardNo: "MM/W17-029S",
            Rarity: "SR",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "8500",
            Soul: "2",
            Traits: ["Magic", ""],
            Triggers: "Soul",
            Flavor: "SECRET",
            Effect: "[C] For each Marker under this, this gains +1500 Power. [A] When you Refresh your Library, you may put the top card of your Library under this as a Marker."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka, Ultimate",
            CardNameJp: "アルティメットまどか",
            CardNo: "MM/W17-030",
            Rarity: "R",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Magic", ""],
            Triggers: "Soul",
            Flavor: "My wish is for all witches to vanish",
            Effect: "[A] When this is placed from hand to the Stage or via CHANGE to the Stage, you may put the top card of your Clock in your Waiting Room. [A] [Send this to Memory] When \"Madoka's Wish\" is placed in the Climax Zone, you may pay cost. If so, search your Library for up to 1 \"'Continue to Fight' Homura\" and put it in the Slot this was in. Afterwards, shuffle your Library, and that Character gains +3000 Power until the end of your Opponent's next turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka, Ultimate",
            CardNameJp: "アルティメットまどか",
            CardNo: "MM/W17-030R",
            Rarity: "RRR",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Magic", ""],
            Triggers: "Soul",
            Flavor: "SECRET",
            Effect: "[A] When this is placed from hand to the Stage or via CHANGE to the Stage, you may put the top card of your Clock in your Waiting Room. [A] [Send this to Memory] When \"Madoka's Wish\" is placed in the Climax Zone, you may pay cost. If so, search your Library for up to 1 \"'Continue to Fight' Homura\" and put it in the Slot this was in. Afterwards, shuffle your Library, and that Character gains +3000 Power until the end of your Opponent's next turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka, Bond with Homura",
            CardNameJp: "ほむらとの絆 まどか",
            CardNo: "MM/W17-031",
            Rarity: "U",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "500",
            Soul: "1",
            Traits: ["Magic", ""],
            Triggers: "None",
            Flavor: "I'll become a magical girl",
            Effect: "[A] [(2)] When this is placed from hand to the Stage, you may pay cost. If so, choose 1 ::Magic:: Character in your Clock and return it to your hand, and put the top card of your Library in your Clock. [A] BOND/\"Homura, Hidden Feelings\" [(1)]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka, Confronting Walpurgis Night",
            CardNameJp: "ワルプルギスの夜に挑むまどか",
            CardNo: "MM/W17-032",
            Rarity: "U",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2000",
            Soul: "1",
            Traits: ["Magic", ""],
            Triggers: "None",
            Flavor: "Goodbye, Homura-chan. Be well",
            Effect: "[C] If you have 2 or fewer other Characters, this gains +1500 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka, Protecting Hope",
            CardNameJp: "希望を守る まどか",
            CardNo: "MM/W17-033",
            Rarity: "U",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "1500",
            Soul: "1",
            Traits: ["Magic", ""],
            Triggers: "Soul",
            Flavor: "I'm happy when I can be of help to others",
            Effect: "[A] When you use the BACKUP of this, choose 1 of your battling GREEN Characters. That Character gains +1000 Power for the turn. [S] [Counter] BACKUP 1500, Level 1 [(1) Discard this card from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Determined",
            CardNameJp: "決意のほむら",
            CardNo: "MM/W17-034",
            Rarity: "U",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "4000",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "Soul",
            Flavor: "No one... believes the future...",
            Effect: "[A] CHANGE [(1) Put this in the Waiting Room] At the beginning of your Draw Phase, you may pay cost. If so, choose a \"Homura, Magical Girl of Time\" in your Waiting Room and put it in the Slot this was in. [S] [Rest this] Choose 1 of your ::Magic:: Characters. That Character gains +1000 Power until the end of your Opponent's next turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Time-Travelling Backwards",
            CardNameJp: "時間遡行者 ほむら",
            CardNo: "MM/W17-035",
            Rarity: "U",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "7500",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "Soul",
            Flavor: "--Repeat. -- I shall repeat this as many times as I need",
            Effect: "[A] When this is placed from hand to the Stage, if there are 5 or fewer cards in your Library, return all cards in your Waiting Room to the Library. If so, shuffle that Library, and choose 1 of your \"Madoka, Fate's Final Destination\", and put up to 2 cards from top of your Library under that Character as Marker, and all your Characters gain +2000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "\"Continue to Fight\" Homura",
            CardNameJp: "“戦い続ける”ほむら",
            CardNo: "MM/W17-036",
            Rarity: "U",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Magic", "Time"],
            Triggers: "Soul",
            Flavor: "I wanted to complain. -- Now, let's go",
            Effect: "[C] RECOLLECTION If \"Madoka, Ultimate\" is in your Memory, this gains +1500 Power. [A] When this is Front Attacked, look at the top card of your Library. Put it either on top of your Library or in the Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka Kaname",
            CardNameJp: "鹿目 まどか",
            CardNo: "MM/W17-037",
            Rarity: "U",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Magic", ""],
            Triggers: "Soul",
            Flavor: "Any rule that interferes, I shall break and change it",
            Effect: "[C] If you have 3 or more other ::Magic:: Characters, this gains +1000 Power. [A] When this is placed from hand to the Stage, all your Characters gain +2000 Power for the turn. [S] [(1)] This gains +2000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura Akemi",
            CardNameJp: "暁美 ほむら",
            CardNo: "MM/W17-038",
            Rarity: "U",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Magic", "Time"],
            Triggers: "Soul",
            Flavor: "I shall use all options at my disposal to deal with fools",
            Effect: "[C] If there are 4 or fewer cards in your Stock, this gains +500 Power and \"[A] ENCORE [Discard a Character card from hand to the Waiting Room]\". [C] Character Opposite this gets -1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Transfer Student",
            CardNameJp: "転校生 ほむら",
            CardNo: "MM/W17-039",
            Rarity: "C",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "1000",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "None",
            Flavor: "A,a,a,Akemi, Ho, Homura. Uh... Pl.. pleased to meet you",
            Effect: "[C] ASSIST All your Characters in front of this gain +500 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Holding onto Bonds",
            CardNameJp: "絆を抱く少女 ほむら",
            CardNo: "MM/W17-040",
            Rarity: "C",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "1000",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "None",
            Flavor: "You are too hard on yourself. Madoka Kaname",
            Effect: "[A] BOND/\"Madoka, Wavering Feelings\" [(1)]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Thinking of Madoka",
            CardNameJp: "まどかを想うほむら",
            CardNo: "MM/W17-041",
            Rarity: "C",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2000",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "None",
            Flavor: "I shall deal with every single witch by myself",
            Effect: "[C] If you have another Character with \"Madoka\" in the name, this gains +1500 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "\"To Protect Everyone\" Madoka",
            CardNameJp: "“みんなを守るために” まどか",
            CardNo: "MM/W17-042",
            Rarity: "C",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2000",
            Soul: "1",
            Traits: ["Magic", ""],
            Triggers: "None",
            Flavor: "Becoming a magical girl would allow me to help a lot of people -- that makes my happiness more than my terror",
            Effect: "[A] When this attacks, choose 1 of your other ::Magic:: Characters. That Character gains +1000 Power until the end of your Opponent's next turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka, Infirmary Officer",
            CardNameJp: "保健係 まどか",
            CardNo: "MM/W17-043",
            Rarity: "C",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Magic", ""],
            Triggers: "None",
            Flavor: "Homura: \"Kaname... Madoka-san. You're the infirmary officer of this class, right?\"",
            Effect: "[A] [(1)] When this attacks, if \"The Girl From the Dream\" is in your Climax Zone, you may pay cost. If so, choose a Character in your Clock and return it to your hand, and put the top card of your Library in your Clock."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Hitomi Shizuki",
            CardNameJp: "志筑 仁美",
            CardNo: "MM/W17-044",
            Rarity: "C",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Music", ""],
            Triggers: "None",
            Flavor: "If I could cut it cleanly like Madoka's mother...",
            Effect: "[A] When this attacks, all your other Characters gain +1 Level for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Black-haired Girl",
            CardNameJp: "黒髪の少女 ほむら",
            CardNo: "MM/W17-045",
            Rarity: "C",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3000",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "None",
            Flavor: "I'm Homura Akemi. Pleased to meet you",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka, Second-year Student of Mitakihara Middle School",
            CardNameJp: "見滝原中学二年生 まどか",
            CardNo: "MM/W17-046",
            Rarity: "C",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "4500",
            Soul: "1",
            Traits: ["Magic", ""],
            Triggers: "None",
            Flavor: "I... I'm being called. Directly within my head, this one's voice",
            Effect: "[A] [Clock] SHIFT Level 1 [S] BRAINSTORM [(1)] Reveal the top 4 cards of your Library and put them in the Waiting Room. For each Climax card revealed this way, choose 1 of your ::Magic:: Characters. That Character gains +2000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka & Homura, Best Friends",
            CardNameJp: "最高の友達 まどか＆ほむら",
            CardNo: "MM/W17-047",
            Rarity: "C",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5000",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "None",
            Flavor: "Homura: \"Because this is the place that girl protected\"",
            Effect: "[A] [(1)] When this attacks, if \"My Best Friend\" is in the Climax Zone, you may pay cost. If so, all your ::Magic:: Characters gain +2500 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka of the Blue Sky",
            CardNameJp: "青空のまどか",
            CardNo: "MM/W17-048",
            Rarity: "C",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5500",
            Soul: "1",
            Traits: ["Magic", ""],
            Triggers: "None",
            Flavor: "That's the self that I want to become one day",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Junko Kaname",
            CardNameJp: "鹿目 詢子",
            CardNo: "MM/W17-049",
            Rarity: "C",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "4000",
            Soul: "1",
            Traits: ["", ""],
            Triggers: "Soul",
            Flavor: "Even though I look like a girl, taking me lightly will be your end, okay?",
            Effect: "[C] All your other Characters whose name includes \"Madoka\" gain +1000 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Lonely Battle",
            CardNameJp: "孤独な戦い ほむら",
            CardNo: "MM/W17-050",
            Rarity: "C",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "6000",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "None",
            Flavor: "Kyubey: \"She is still wishing for hope\"",
            Effect: "[A] [(2)] When \"Time Manipulation\" is placed in your Climax Zone, you may pay cost. If so, this gains \"[C] When this attacks, you may instead choose a Character in your Opponent's Back Row and have this Front Attack that Character as Defending Character\" for the turn. [A] ENCORE [Discard a Character card from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "\"Stage Device's Witch\" Walpurgis Night",
            CardNameJp: "“舞台装置の魔女”ワルプルギスの夜",
            CardNo: "MM/W17-051",
            Rarity: "C",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "8500",
            Soul: "2",
            Traits: ["Magic", ""],
            Triggers: "Soul",
            Flavor: "Homura: \"Walpurgis Night will come to this town\"",
            Effect: "[S] [(2)] This gains +5000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka, Feather-like Skirt",
            CardNameJp: "ふわふわスカート まどか",
            CardNo: "MM/W17-052",
            Rarity: "C",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "9000",
            Soul: "2",
            Traits: ["Magic", ""],
            Triggers: "Soul",
            Flavor: "I, I should really think about it, even if it's just the outfit...",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Law of Cycles",
            CardNameJp: "円環の理",
            CardNo: "MM/W17-053",
            Rarity: "U",
            Color: "Green",
            Side: "Weiss",
            Type: "Event",
            Level: "1",
            Cost: "1",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "None",
            Flavor: "Your prayers will not result in the end of despair",
            Effect: "Search your Library for up to 1 ::Magic:: Character, reveal it, and put it in your hand. Shuffle your Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Meaningless Chain",
            CardNameJp: "無意味な連鎖",
            CardNo: "MM/W17-054",
            Rarity: "U",
            Color: "Green",
            Side: "Weiss",
            Type: "Event",
            Level: "2",
            Cost: "1",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "None",
            Flavor: "Madoka: \"... You mean as long as she has hope, she cannot be saved?\"",
            Effect: "Look at the top 3 cards of your Opponent's Library and choose up to 1 of them and put it at the bottom of the Lbirary. Put the rest on top of the Library in any order."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka's Wish",
            CardNameJp: "まどかの願い",
            CardNo: "MM/W17-055",
            Rarity: "CR",
            Color: "Green",
            Side: "Weiss",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "Treasure",
            Flavor: "I -- shall no longer need to despair",
            Effect: "[C] All your Characters gain +1000 Power and +1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "No Longer Relying on Others",
            CardNameJp: "もう誰にも頼らない",
            CardNo: "MM/W17-056",
            Rarity: "CC",
            Color: "Green",
            Side: "Weiss",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "Treasure",
            Flavor: "This is not my battlefield",
            Effect: "[C] All your Characters gain +1000 Power and +1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Time Manipulation",
            CardNameJp: "時間操作",
            CardNo: "MM/W17-057",
            Rarity: "CC",
            Color: "Green",
            Side: "Weiss",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "2 Soul",
            Flavor: "I live in a different time than Madoka",
            Effect: "[A] When this is placed from hand to the Climax Zone, draw a card, and choose 1 of your Charcaters. That Character gains +2000 Power and +1 Soul for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "My Best Friend",
            CardNameJp: "わたしの、最高の友達",
            CardNo: "MM/W17-058",
            Rarity: "CC",
            Color: "Green",
            Side: "Weiss",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "Stock",
            Flavor: "Just remember that. Don't ever forget it.",
            Effect: "[C] All your Characters gain +1000 Power and +1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Don't Tell Anyone in Class!",
            CardNameJp: "クラスのみんなには、内緒だよ！",
            CardNo: "MM/W17-059",
            Rarity: "CC",
            Color: "Green",
            Side: "Weiss",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "2 Soul",
            Flavor: "Kyubey: \"They are magical girls\"",
            Effect: "[C] All your Characters gain +2 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "The Girl From the Dream",
            CardNameJp: "夢に出てきた少女",
            CardNo: "MM/W17-060",
            Rarity: "CC",
            Color: "Green",
            Side: "Weiss",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "2 Soul",
            Flavor: "Homura: \"Madoka Kaname, do you consider your life to be valuable?\"",
            Effect: "[A] When this is placed from hand to the Stage, put the top card of your Library in your Stock, and all your Characters gain +1 Soul for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko, Battle-loving",
            CardNameJp: "好戦的 杏子",
            CardNo: "MM/W17-061",
            Rarity: "RR",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "4000",
            Soul: "1",
            Traits: ["Magic", "Sweets"],
            Triggers: "None",
            Flavor: "She looks like such an amateur. I'll finish her off instantly",
            Effect: "[A] ENCORE [Discard a Character card from hand to the Waiting Room] [S] [Rest 1 of your ::Magic:: Characters] This gains +1500 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko, Battle-loving",
            CardNameJp: "好戦的 杏子",
            CardNo: "MM/W17-061R",
            Rarity: "RRR",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "4000",
            Soul: "1",
            Traits: ["Magic", "Sweets"],
            Triggers: "None",
            Flavor: "SECRET",
            Effect: "[A] ENCORE [Discard a Character card from hand to the Waiting Room] [S] [Rest 1 of your ::Magic:: Characters] This gains +1500 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko Sakura",
            CardNameJp: "佐倉 杏子",
            CardNo: "MM/W17-062",
            Rarity: "RR",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Magic", "Sweets"],
            Triggers: "Soul",
            Flavor: "Isn't that right? A story that ends with victory for love and courage",
            Effect: "[A] When this is placed from hand to the Stage or via CHANGE to the Stage, you may choose a ::Magic:: Character in your Waiting Room and return it to your hand. [S] [(1) Rest 2 of your Characters] This gains +2000 Power and \"[A] When the Battle Opponent of this becomes Reversed, you may put that Character on top of the Library\" for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko Sakura",
            CardNameJp: "佐倉 杏子",
            CardNo: "MM/W17-062SP",
            Rarity: "SP",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Magic", "Sweets"],
            Triggers: "Soul",
            Flavor: "SECRET",
            Effect: "[A] When this is placed from hand or via CHANGE to the Stage, you may choose a ::Magic:: Character in your Waiting Room and return it to your hand. [S] [(1) Rest 2 of your Characters] This gains +2000 Power and \"[A] When the Battle Opponent of this becomes Reversed, you may put that Character on top of the Library\" for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko, Sharing Apples",
            CardNameJp: "林檎のおすそわけ 杏子",
            CardNo: "MM/W17-063",
            Rarity: "R",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "500",
            Soul: "1",
            Traits: ["Magic", "Sweets"],
            Triggers: "None",
            Flavor: "Want one?",
            Effect: "[C] All your other \"Sayaka, Second-year Student of Mitakihara Middle School\" gain +1000 Power. [A] BOND/\"Sayaka, Second-year Student of Mitakihara Middle School\" [(1)]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko, Multi-Section Spear",
            CardNameJp: "多節槍 杏子",
            CardNo: "MM/W17-064",
            Rarity: "R",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "2000",
            Soul: "1",
            Traits: ["Magic", "Sweets"],
            Triggers: "Soul",
            Flavor: "What's with you? Whose ally are you?",
            Effect: "[C] ASSIST All your Characters in front of this gain +X Power. X = 500 times number of your Characters with ASSIST [A] [(2)] When this is placed from hand to the Stage, you may pay cost. If so, choose a ::Magic:: Character in your Waiting Room and return it to your hand."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko, Selfish One",
            CardNameJp: "利己主義者 杏子",
            CardNo: "MM/W17-065",
            Rarity: "R",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "8000",
            Soul: "1",
            Traits: ["Magic", "Sweets"],
            Triggers: "Soul",
            Flavor: "What are you doing like a chicken about to lay an egg",
            Effect: "[A] [(2)] When this attacks, if \"Sayaka VS Kyoko\" is in the Climax Zone, you may pay cost. If so, choose up to 2 Characters in your Waiting Room and return it to your hand."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko, Selfish One",
            CardNameJp: "利己主義者 杏子",
            CardNo: "MM/W17-065S",
            Rarity: "SR",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "8000",
            Soul: "1",
            Traits: ["Magic", "Sweets"],
            Triggers: "Soul",
            Flavor: "SECRET",
            Effect: "[A] [(2)] When this attacks, if \"Sayaka VS Kyoko\" is in the Climax Zone, you may pay cost. If so, choose up to 2 Characters in your Waiting Room and return it to your hand."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko, Shouting",
            CardNameJp: "吠える杏子",
            CardNo: "MM/W17-066",
            Rarity: "R",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "8000",
            Soul: "2",
            Traits: ["Magic", "Sweets"],
            Triggers: "Soul",
            Flavor: "Who are you!? What did you do to Sayaka!?",
            Effect: "[C] If you have another Character whose name includes \"Sayaka\", this gains +1500 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko, Shouting",
            CardNameJp: "吠える杏子",
            CardNo: "MM/W17-066S",
            Rarity: "SR",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "8000",
            Soul: "2",
            Traits: ["Magic", "Sweets"],
            Triggers: "Soul",
            Flavor: "SECRET",
            Effect: "[C] If you have another Character whose name includes \"Sayaka\", this gains +1500 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyubey, Supporting Role",
            CardNameJp: "サポート役 キュゥべえ",
            CardNo: "MM/W17-067",
            Rarity: "U",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Alien", "Magic"],
            Triggers: "None",
            Flavor: "I don't understand. Why do humans have to care so much about where their soul is?",
            Effect: "[C] If this is in the Front Row, your other ::Magic:: Character in the Front Row Center Slot gains \"[A] ENCORE [Put the top card of your Library in your Clock]\"."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko, Confession of the Past",
            CardNameJp: "過去の告白 杏子",
            CardNo: "MM/W17-068",
            Rarity: "U",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3500",
            Soul: "1",
            Traits: ["Magic", "Sweets"],
            Triggers: "None",
            Flavor: "My family consistently lacked food",
            Effect: "[A] When this is placed from hand to the Stage, if you have 3 or more Climax cards in your Waiting Room, put the top card of your Library in your Clock."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko, Wishing for a Miracle",
            CardNameJp: "奇跡を願う杏子",
            CardNo: "MM/W17-069",
            Rarity: "U",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5000",
            Soul: "1",
            Traits: ["Magic", "Sweets"],
            Triggers: "None",
            Flavor: "Please, God... Just once in my life...show me a happy dream...",
            Effect: "[A] [Discard a card from your hand to the Waiting Room] When \"Being on Your Own is Lonely\" is placed in your Climax Zone, if this is in the Front Row, you may pay cost. If so, choose a Level 2 or lower Character in your Opponent's Front Row and put it in the Waiting Room, and at the end of the turn, put this in the Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko in the Back Alley",
            CardNameJp: "路地裏の杏子",
            CardNo: "MM/W17-070",
            Rarity: "U",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "4000",
            Soul: "1",
            Traits: ["Magic", "Sweets"],
            Triggers: "Soul",
            Flavor: "I need to talk to you. Will you come with me?",
            Effect: "[C] ASSIST All your Characters in front of this gain +1000 Power. [A] CHANGE [(1) Put this in the Waiting Room] At the beginning of your Draw Phase, you may pay cost. If so, choose a \"Kyoko Sakura\" in your Waiting Room and put it in the Slot this was in."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko, Red Soul Gem",
            CardNameJp: "赤いソウルジェム 杏子",
            CardNo: "MM/W17-071",
            Rarity: "C",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "1000",
            Soul: "1",
            Traits: ["Magic", "Sweets"],
            Triggers: "None",
            Flavor: "You got something to say?",
            Effect: "[C] ASSIST All your Characters in front of this gain +500 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko, Farewell on the Subway Platform",
            CardNameJp: "地下鉄ホームでの別れ 杏子",
            CardNo: "MM/W17-072",
            Rarity: "C",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2000",
            Soul: "1",
            Traits: ["Magic", "Sweets"],
            Triggers: "None",
            Flavor: "Are you always going to be that stubborn?",
            Effect: "[A] When this becomes Reversed, if its Battle Opponent is Level 0 or lower, you may Reverse that Character."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko, New Magical Girl",
            CardNameJp: "新たなる魔法少女 杏子",
            CardNo: "MM/W17-073",
            Rarity: "C",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3000",
            Soul: "1",
            Traits: ["Magic", "Sweets"],
            Triggers: "None",
            Flavor: "Kyubey: \"I really didn't expect you to come\"",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko who Finally Arrived",
            CardNameJp: "やって来た杏子",
            CardNo: "MM/W17-074",
            Rarity: "C",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "1500",
            Soul: "1",
            Traits: ["Magic", "Sweets"],
            Triggers: "None",
            Flavor: "But I'm not just going to let some rookie chick take this perfect area right from under my nose",
            Effect: "[S] [Counter] BACKUP 1500, Level 1 [Discard this card from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyubey, Extra-terrestial Lifeform",
            CardNameJp: "地球外生命体 キュゥべえ",
            CardNo: "MM/W17-075",
            Rarity: "C",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "7000",
            Soul: "1",
            Traits: ["Alien", "Magic"],
            Triggers: "None",
            Flavor: "Hah, it's so hard to communicate with humans",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko, Magical Girl of the Spear",
            CardNameJp: "槍の魔法少女 杏子",
            CardNo: "MM/W17-076",
            Rarity: "C",
            Color: "Red",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "7500",
            Soul: "2",
            Traits: ["Magic", "Sweets"],
            Triggers: "Soul",
            Flavor: "Heh, unwelcomed guys have unwelcomed friends too, it seems",
            Effect: "[C] If you have 3 or more other ::Magic:: Characters, this gains +1000 Power. [A] ENCORE [Discard a Character card from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyoko's Determination",
            CardNameJp: "杏子の覚悟",
            CardNo: "MM/W17-077",
            Rarity: "U",
            Color: "Red",
            Side: "Weiss",
            Type: "Event",
            Level: "1",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "All your ::Magic:: Characters gain +1500 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "A Magical Girl Appears",
            CardNameJp: "魔法少女現る",
            CardNo: "MM/W17-078",
            Rarity: "U",
            Color: "Red",
            Side: "Weiss",
            Type: "Event",
            Level: "2",
            Cost: "1",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "None",
            Flavor: "Can we crush that girl?",
            Effect: "Choose up to 2 Characters in your Waiting Room and return it to your hand, choose a card in your hand and put it in the Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka VS Kyoko",
            CardNameJp: "さやか VS 杏子",
            CardNo: "MM/W17-079",
            Rarity: "CR",
            Color: "Red",
            Side: "Weiss",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "Salvage",
            Flavor: "I dove in half-hearted.... it really bothers me",
            Effect: "[C] All your Characters gain +1000 Power and +1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Being on Your Own is Lonely",
            CardNameJp: "独りぼっちは、寂しいもんな",
            CardNo: "MM/W17-080",
            Rarity: "CC",
            Color: "Red",
            Side: "Weiss",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "2 Soul",
            Flavor: "Being on your own is lonely... That's alright. Let's go together. Sayaka...",
            Effect: "[A] When this is placed from hand to the Climax Zone, draw a card, and choose 1 of your Characters. That Character gains +2000 Power and +1 Soul for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Rookie Magical Girl",
            CardNameJp: "新人魔法少女 さやか",
            CardNo: "MM/W17-081",
            Rarity: "RR",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "3000",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "None",
            Flavor: "I shall protect this town from now on",
            Effect: "[C] ASSIST All your Characters in front of this gain \"[A] ENCORE [Discard a Character card from hand to the Waiting Room]\" [A] CHANGE [(1) Put this in the Waiting Room] At the beginning of your Draw Phase, you may pay cost. If so, choose a \"Sayaka, Hollowed Eyes\" in your Waiting Room and put it in the Slot this was in."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Rookie Magical Girl",
            CardNameJp: "新人魔法少女 さやか",
            CardNo: "MM/W17-081R",
            Rarity: "RRR",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "3000",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "None",
            Flavor: "SECRET",
            Effect: "[C] ASSIST All your Characters in front of this gain \"[A] ENCORE [Discard a Character card from hand to the Waiting Room]\" [A] CHANGE [(1) Put this in the Waiting Room] At the beginning of your Draw Phase, you may pay cost. If so, choose a \"Sayaka, Hollowed Eyes\" in your Waiting Room and put it in the Slot this was in."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka Miki",
            CardNameJp: "美樹 さやか",
            CardNo: "MM/W17-082",
            Rarity: "RR",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Magic", "Love"],
            Triggers: "Soul",
            Flavor: "I wished for this power not just because I want to fight witches, but also to protect people who are important to me",
            Effect: "[C] For each other ::Magic:: Character you have, this gains +500 Power. [A] When this is placed from hand to the Stage, you may put the top card of your Clock in the Waiting Room. [A] When this becomes Reversed in Battle, Send this to Memory."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka Miki",
            CardNameJp: "美樹 さやか",
            CardNo: "MM/W17-082SP",
            Rarity: "SP",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Magic", "Love"],
            Triggers: "Soul",
            Flavor: "SECRET",
            Effect: "[C] For each other ::Magic:: Character you have, this gains +500 Power. [A] When this is placed from hand to the Stage, you may put the top card of your Clock in the Waiting Room. [A] When this becomes Reversed in Battle, Send this to Memory."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Fighting for People",
            CardNameJp: "人の為に戦うさやか",
            CardNo: "MM/W17-083",
            Rarity: "R",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "500",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "None",
            Flavor: "I do not regret anything that I wished for others",
            Effect: "[C] All your other \"Kyoko, Shouting\" gain +500 Power and \"[A] ENCORE [Discard a Character card from your hand to the Waiting Room]\". [C] ASSIST All your Characters in front of this gain +500 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Admiration for Mami",
            CardNameJp: "マミへの憧れ さやか",
            CardNo: "MM/W17-084",
            Rarity: "R",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "1500",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "None",
            Flavor: "Sayaka: \"Mami-san looks so good!\"",
            Effect: "[A] When this is placed from hand to the Stage, look at the top card of your Library and put it either on top or bottom of the Library. [A] When this attacks, reveal the top card of your Library. If it's a ::Magic:: Character, put it in your hand and discard a card from your hand to the Waiting Room. (Otherwise put the card back where it was)"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Healing Prayer",
            CardNameJp: "癒しの祈り さやか",
            CardNo: "MM/W17-085",
            Rarity: "R",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "6500",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "None",
            Flavor: "Kyubey: \"She contracted with healing prayers and became a magical girl\"",
            Effect: "[A] When this becomes Reversed in Battle, put the top card of your Library in your Clock and Rest this."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Healing Prayer",
            CardNameJp: "癒しの祈り さやか",
            CardNo: "MM/W17-085S",
            Rarity: "SR",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "6500",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "None",
            Flavor: "SECRET",
            Effect: "[A] When this becomes Reversed in Battle, put the top card of your Library in your Clock and Rest this."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Hollow Eyes",
            CardNameJp: "虚ろな目 さやか",
            CardNo: "MM/W17-086",
            Rarity: "R",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "5000",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "Soul",
            Flavor: "Don't, get in my way...",
            Effect: "[C] All your other Characters gain +1000 Power during your Opponent's turn. [A] [(1) Put this in the Waiting Room] When \"I've Been Such A Fool\" is placed in your Climax Zone, you may pay cost. If so, choose either 1 \"'Mermaid Witch'\" or 1 \"Sayaka, Battling While Hurting\" in your Waiting Room and put it in the Slot this was in, draw a card, and the chosen Character gains +1500 Power until the end of your Opponent's next turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Hollow Eyes",
            CardNameJp: "虚ろな目 さやか",
            CardNo: "MM/W17-086S",
            Rarity: "SR",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "5000",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "Soul",
            Flavor: "SECRET",
            Effect: "[C] All your other Characters gain +1000 Power during your Opponent's turn. [A] [(1) Put this in the Waiting Room] When \"I've Been Such A Fool\" is placed in your Climax Zone, you may pay cost. If so, choose either 1 \"'Mermaid Witch'\" or 1 \"Sayaka, Battling While Hurting\" in your Waiting Room and put it in the Slot this was in, draw a card, and the chosen Character gains +1500 Power until the end of your Opponent's next turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Classmate",
            CardNameJp: "クラスメイト さやか",
            CardNo: "MM/W17-087",
            Rarity: "U",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3500",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "None",
            Flavor: "No, Madoka's mother is always so nice",
            Effect: "[C] If this is in the Front Row, this does not Stand during your Stand Phase."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Found Her Wish",
            CardNameJp: "願いを見つけたさやか",
            CardNo: "MM/W17-088",
            Rarity: "U",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5000",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "None",
            Flavor: "I've found what I would wish for",
            Effect: "[A] [(1) Put this in the Waiting Room] When \"Both Miracles And Magic Exist\" is placed in your Climax Zone, you may pay cost. If so, choose up to 1 \"Sayaka, Hollowed Eyes\" in your hand and put it in the Slot this was in, and choose a Level 0 or lower Character in your Waiting Room whose name includes \"Kamijou\" and put it in any Slot on Stage."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Ally of Justice",
            CardNameJp: "正義の味方 さやか",
            CardNo: "MM/W17-089",
            Rarity: "U",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "8000",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "Soul",
            Flavor: "Even from now on, the peace of Mitakihara City shall be protected by me, Magical Girl Sayaka-chan!",
            Effect: "[C] If you have 3 or more other ::Magic:: Characters, this gains +1000 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "\"Mermaid Witch\"",
            CardNameJp: "“人魚の魔女”",
            CardNo: "MM/W17-090",
            Rarity: "U",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Magic", "Music"],
            Triggers: "Soul",
            Flavor: "Madoka: \"Hey, please... please return to the old Sayaka-chan! Please return to my favorite Sayaka-chan!\"",
            Effect: "[A] [Discard a Character card from hand to the Waiting Room] When this is placed from hand to the Stage, you may pay cost. If not, put this in the Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Confrontation",
            CardNameJp: "対決するさやか",
            CardNo: "MM/W17-091",
            Rarity: "C",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "1000",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "None",
            Flavor: "Those who were attacked by witches... You didn't even help them!?",
            Effect: "[A] BOND/\"Kyoko, Wishing for a Miracle\" [(1)]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyousuke Kamijou",
            CardNameJp: "上条 恭介",
            CardNo: "MM/W17-092",
            Rarity: "C",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Music", ""],
            Triggers: "None",
            Flavor: "Sayaka: \"You must wish for things that are somewhat related to you\"",
            Effect: "[A] When this attacks, look at the top card of your Library, and put it either on top or bottom of the Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Childhood Friend of Kamijou-kun",
            CardNameJp: "上条君の幼なじみ さやか",
            CardNo: "MM/W17-093",
            Rarity: "C",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3000",
            Soul: "1",
            Traits: ["Magic", "Music"],
            Triggers: "None",
            Flavor: "Wow",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Second-year Student of Mitakihara Middle School",
            CardNameJp: "見滝原中学二年生 さやか",
            CardNo: "MM/W17-094",
            Rarity: "C",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5500",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "None",
            Flavor: "-- None --",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Magical Girl of the Sword",
            CardNameJp: "剣の魔法少女 さやか",
            CardNo: "MM/W17-095",
            Rarity: "C",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "2000",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[S] [Counter] BACKUP 2000, Level 1 [(1) Discard this from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Battling While Hurting",
            CardNameJp: "傷つきながら戦うさやか",
            CardNo: "MM/W17-096",
            Rarity: "C",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "9500",
            Soul: "2",
            Traits: ["Magic", "Love"],
            Triggers: "Soul",
            Flavor: "If you can do that, all the pain... will completely go away...",
            Effect: "[A] When this becomes Reversed in Battle, put the top card of your Library in your Clock, and Rest this. [S] [Rest 1 of your ::Magic:: Characters] This gains +1000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Incubator",
            CardNameJp: "孵卵器",
            CardNo: "MM/W17-097",
            Rarity: "U",
            Color: "Blue",
            Side: "Weiss",
            Type: "Event",
            Level: "2",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "None",
            Flavor: "Even though there are lots of replacements, being destroyed meaninglessly is still troublesome",
            Effect: "Choose 1 of your Standing ::Magic:: Characers and Rest it. If so, draw up to 2 cards, and discard a card from your hand to the Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka's Wish",
            CardNameJp: "さやかの願い",
            CardNo: "MM/W17-098",
            Rarity: "U",
            Color: "Blue",
            Side: "Weiss",
            Type: "Event",
            Level: "2",
            Cost: "1",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "None",
            Flavor: "There's no reason for me to regret",
            Effect: "[Counter] Choose 1 of your Characters with \"Sayaka\" in the name and put it in the Waiting Room. If so, return the top card of your Clock to your hand, and Send this to Memory."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "I've Been Such A Fool",
            CardNameJp: "あたしって、ほんとバカ",
            CardNo: "MM/W17-099",
            Rarity: "CR",
            Color: "Blue",
            Side: "Weiss",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "Draw",
            Flavor: "Resentment and pain took root in my own heart, I'm even hurting my dearest friend now",
            Effect: "[C] All your Characters gain +1000 Power and +1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Both Miracles And Magic Exist",
            CardNameJp: "奇跡も、魔法も、あるんだよ",
            CardNo: "MM/W17-100",
            Rarity: "CC",
            Color: "Blue",
            Side: "Weiss",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "2 Soul",
            Flavor: "This is my final strike--!",
            Effect: "[C] All your Characters gain +2 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Challenging Walpurgis Night",
            CardNameJp: "ワルプルギスの夜に挑むほむら",
            CardNo: "MM/W17-101",
            Rarity: "TD",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "4500",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "None",
            Flavor: "This time I will end this",
            Effect: "[A] When this attacks, look at up to 2 cards from the top of your Library and choose 1 of them to put on top of the Library. Put the rest in your Waiting Room."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka & Kyoko, Same Wish",
            CardNameJp: "同じ願い さやか＆杏子",
            CardNo: "MM/W17-102",
            Rarity: "TD",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "2",
            Power: "8500",
            Soul: "2",
            Traits: ["Magic", "Love"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[C] During your Opponent's turn, for each other ::Magic:: Character you have, this gains +500 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Lonely Battle",
            CardNameJp: "孤独な戦い ほむら",
            CardNo: "MM/W17-103",
            Rarity: "TD",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2000",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "None",
            Flavor: "I alone am enough",
            Effect: "[C] If you have no other Characters, this gains +1 Level and +1500 Power. [A] [Clock] Shift Level 0"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Smiling",
            CardNameJp: "笑顔のさやか",
            CardNo: "MM/W17-104",
            Rarity: "TD",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "2500",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "Soul",
            Flavor: "Even though it's the first time, did it come out well? My performance",
            Effect: "[C] ASSIST All your Characters in front of this gain +X Power, where X = 500 times number of Characters with ASSIST you have. [A] ENCORE [Discard a Character card from your hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka, Normal Girl",
            CardNameJp: "平凡な少女 まどか",
            CardNo: "MM/W17-105",
            Rarity: "TD",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "1000",
            Soul: "1",
            Traits: ["Magic", ""],
            Triggers: "None",
            Flavor: "That's so nice... I want to have one too... a love letter",
            Effect: "[C] ASSIST All your Characters in front of this gain +500 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura, Black-haired Girl",
            CardNameJp: "黒髪の少女 ほむら",
            CardNo: "MM/W17-T01",
            Rarity: "TD",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3000",
            Soul: "1",
            Traits: ["Magic", "Time"],
            Triggers: "None",
            Flavor: "I'm Homura Akemi. Pleased to meet you",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka, Infirmary Officer",
            CardNameJp: "保健係 まどか",
            CardNo: "MM/W17-T02",
            Rarity: "TD",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Magic", ""],
            Triggers: "None",
            Flavor: "Homura: \"Kaname... Madoka-san. You're the infirmary officer of this class, right?\"",
            Effect: "[A] [(1)] When this attacks, if \"The Girl From the Dream\" is in your Climax Zone, you may pay cost. If so, choose a Character in your Clock and return it to your hand, and put the top card of your Library in your Clock."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka of the Blue Sky",
            CardNameJp: "青空のまどか",
            CardNo: "MM/W17-T03",
            Rarity: "TD",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5500",
            Soul: "1",
            Traits: ["Magic", ""],
            Triggers: "None",
            Flavor: "That's the self that I want to become one day",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Madoka Kaname",
            CardNameJp: "鹿目 まどか",
            CardNo: "MM/W17-T04",
            Rarity: "TD",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Magic", ""],
            Triggers: "Soul",
            Flavor: "I really thought that it was nice to be a magical girl",
            Effect: "[C] If you have 3 or more other ::Magic:: Characters, this gains +1000 Power. [A] When this is placed from hand to the Stage, all your Characters gain +2000 Power for the turn. [S] [(1)] This gains +2000 Power for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Homura Akemi",
            CardNameJp: "暁美 ほむら",
            CardNo: "MM/W17-T05",
            Rarity: "TD",
            Color: "Green",
            Side: "Weiss",
            Type: "Character",
            Level: "3",
            Cost: "2",
            Power: "10000",
            Soul: "2",
            Traits: ["Magic", "Time"],
            Triggers: "Soul",
            Flavor: "I'm an ally of those who're cool and calm, and enemy of those idiots who bicker for no reason",
            Effect: "[C] If there are 4 or fewer cards in your Stock, this gains +500 Power and \"[A] ENCORE [Discard a Character card from hand to the Waiting Room]\". [C] Character Opposite this gets -1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Law of Cycles",
            CardNameJp: "円環の理",
            CardNo: "MM/W17-T06",
            Rarity: "TD",
            Color: "Green",
            Side: "Weiss",
            Type: "Event",
            Level: "1",
            Cost: "1",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "None",
            Flavor: "Your prayers shall not end in despair",
            Effect: "Search your Library for up to 1 ::Magic:: Character, reveal it, and put it in your hand. Shuffle your Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "No Longer Relying on Others",
            CardNameJp: "もう誰にも頼らない",
            CardNo: "MM/W17-T07",
            Rarity: "TD",
            Color: "Green",
            Side: "Weiss",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "Treasure",
            Flavor: "I don't need to rely on others anymore. I don't need anyone else to understand me",
            Effect: "[C] All your Characters gain +1000 Power and +1 Soul."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "The Girl From the Dream",
            CardNameJp: "夢に出てきた少女",
            CardNo: "MM/W17-T08",
            Rarity: "TD",
            Color: "Green",
            Side: "Weiss",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "2 Soul",
            Flavor: "Madoka: \"Ah, Akemi-san?\" Homura: \"Just call me Homura\"",
            Effect: "[A] When this is placed from hand to the Stage, put the top card of your Library in your Stock, and all your Characters gain +1 Soul for the turn."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Kyousuke Kamijou",
            CardNameJp: "上条 恭介",
            CardNo: "MM/W17-T09",
            Rarity: "TD",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "2500",
            Soul: "1",
            Traits: ["Music", ""],
            Triggers: "None",
            Flavor: "Sayaka: \"You must wish for things that are somewhat related to you\"",
            Effect: "[A] When this attacks, look at the top card of your Library, and put it either on top or bottom of the Library."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Childhood Friend of Kamijou-kun",
            CardNameJp: "上条君の幼なじみ さやか",
            CardNo: "MM/W17-T10",
            Rarity: "TD",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "0",
            Cost: "0",
            Power: "3000",
            Soul: "1",
            Traits: ["Magic", "Music"],
            Triggers: "None",
            Flavor: "Wow",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Second-year Student of Mitakihara Middle School",
            CardNameJp: "見滝原中学二年生 さやか",
            CardNo: "MM/W17-T11",
            Rarity: "TD",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "0",
            Power: "5500",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "None",
            Flavor: "..... This is continuing from yesterday?",
            Effect: "-- None --"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Magical Girl of the Sword",
            CardNameJp: "剣の魔法少女 さやか",
            CardNo: "MM/W17-T12",
            Rarity: "TD",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "1",
            Cost: "1",
            Power: "2000",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "Soul",
            Flavor: "-- None --",
            Effect: "[S] [Counter] BACKUP 2000, Level 1 [(1) Discard this from hand to the Waiting Room]"
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Sayaka, Ally of Justice",
            CardNameJp: "正義の味方 さやか",
            CardNo: "MM/W17-T13",
            Rarity: "TD",
            Color: "Blue",
            Side: "Weiss",
            Type: "Character",
            Level: "2",
            Cost: "1",
            Power: "8000",
            Soul: "1",
            Traits: ["Magic", "Love"],
            Triggers: "Soul",
            Flavor: "Even from now on, peace of Mitakihara City shall be protected by me, Magical Girl Sayaka-chan!",
            Effect: "[C] If you have 3 or more other ::Magic:: Characters, this gains +1000 Power."
        });
        gate.cardset[cardsetCode].Cards.push({
            CardName: "Both Miracles And Magic Exist",
            CardNameJp: "奇跡も、魔法も、あるんだよ",
            CardNo: "MM/W17-T14",
            Rarity: "TD",
            Color: "Blue",
            Side: "Weiss",
            Type: "Climax",
            Level: "0",
            Cost: "0",
            Power: "0",
            Soul: "0",
            Traits: ["", ""],
            Triggers: "2 Soul",
            Flavor: "This is the final strike-!",
            Effect: "[C] All your Characters gain +2 Soul."
        });
    };
}(window.gate = window.gate || {}));
